- src/main/java/carpet/mixins/BlockPlacementDispenserBehaviourMixin.java
- src/main/resources/carpet.mixins.json
Fixes the behaviour of dispensers to remove 2 shulker boxes from a stack instead of 1
Basically the same as in 1.13.2
> Fix for shulker dispenser behaviour

- src/main/java/carpet/CarpetSettings.java
- src/main/java/carpet/mixins/PlayerEntityMixin.java
Fixes #139 and overwrites the default method of getMaxNetherPortalTime to something similar of the vanilla one but instead of returning constant numbers, it returns carpet rules.
> make the nether portal delays better

- docs/scarpet/api/Auxiliary.md
- docs/scarpet/api/BlockIterations.md
- docs/scarpet/api/BlocksAndWorldAccess.md
- docs/scarpet/api/Entities.md
In the first half of ..\docs\scarpet\api, I have fixed many grammer, spelling, and consistency issues, as well as clarified some things that lacked explanation.
Let me know if there's anything that I can do to improve my contribution here.
> Fix: typos in first half of ..\docs\scarpet\api

- docs/scarpet/api/Auxiliary.md
I think that is a correct description. Feel free to change it if you think there is a better way.
> Corrected killed_by description

- src/main/java/carpet/CarpetSettings.java
- src/main/java/carpet/mixins/BastionRemnantFeatureMixin.java
- src/main/resources/carpet.mixins.json
The way this setup would work: 
piglin brutes: weight : 5, minimum group size: 1, maximum group size: 2
piglins : weight : 10, minimum group size: 2, maximum group size: 4
This is currently not very helpful as the piglin brute doesn't drop much experience and doesn't drop interesting loot, however this is likely to change in a future version given the difficulty that the mob presents. 
Please let me know of any issues with this and I will try to fix quickly.
> Add the rule bruteSpawningInBationRemnants

- src/main/java/carpet/commands/PlayerCommand.java
- src/main/java/carpet/helpers/EntityPlayerActionPack.java
Hi. This pull request adds the ability for fake players to look at a location in the world with `/player <name> look at <x> <y> <z>` as an alternative to supplying cardinal directions or angles. This is useful if you ever want to have a fake player do something that requires precise aim like activating a button.
Here's a quick demo of the change in action: https://youtu.be/njLHSUuTt44
> Allow "/player look" to target locations in the world with "/player look at"

- src/main/java/carpet/CarpetExtension.java
- src/main/java/carpet/utils/HUDController.java
- src/main/resources/assets/carpet/lang/zh_cn.json
It's currently not avaliable for carpet extension to add its own HUD loggers without mixin into fabric carpet.
What I did is add a extra method`onUpdateHUD` in `CarpetExtension` Interface and invoke it after every fabric-carpet HUD loggers have finished their jobs and before the logging message is sent to players.
I'm not 100% sure if these 2 lines of code work since I don't know how to test that qwq
One more feature suggestion: give HUD loggers a priority number about who will be on the top and who will be at the bottom. That might be useful but idk xd
> HUD logger hook for carpet extensions

- docs/scarpet/Full.md
- docs/scarpet/language/LoopsAndHigherOrderFunctions.md
Added `expr` to the args of while() in both places in the documentation
I noticed it was missing the other day, so here's a PR adding the args
> Corrected while() documentation

- src/main/java/carpet/fakes/ThreadedAnvilChunkStorageInterface.java
- src/main/java/carpet/mixins/ServerChunkManager_tickMixin.java
- src/main/java/carpet/mixins/ThreadedAnvilChunkStorage_scarpetChunkCreationMixin.java
Fixes the timing issue when using `/tick freeze`. Since `/tick freeze` skips chunk ticking also skips syncing chunk updates with clients, block updates are only visible to the clients after a `/tick step`. So some non-delay blocks like as redstone lamps or fence gates would behave as if there's a one tick delay when using `/tick step`. Blocks updated in block actions like pistons would make things worse since they sync with clients instantly. These issues make the timing analyse of redstone contraptions with `/tick freeze` very inconvenient.
> Always flush chunk updates when tick freezes

- src/main/resources/assets/carpet/scripts/ai_tracker.sc
Fixes #430 
Basically it showed breeding_age of 0 as red, when in fact it ought to be green, as it is a necessary requirement for breeding of villagers.
> Ai_Tracker app bug

- src/main/java/carpet/script/CarpetEventServer.java
It's not possible to create a new event outside the carpet.script package (Commit 3105d5bb719338a511eeac7ee3a3500c6a562f88 fix)
> Made the Event Constructor public

- README.md
I hope i did this right, i added all the extensions i know of to the wiki page: https://github.com/gnembon/fabric-carpet/wiki/List-of-Carpet-extensions
I only added the link to the extension, but people could add descriptions too i guess.
> Added link in readme to the carpet extension list

- src/main/java/carpet/helpers/BlockRotator.java
Resolves #509
This could also easily be amended to work with all pillar blocks, which includes Hay, logs, and other blocks that face in the X, Y or Z axes.
Unfortunately the builtin rotate function on pillar blocks only switches them between X and Z axes, so this solution is a bit less elegant than calling `state.rotate`
> Add chain rotation to flippinCactus

- .github/workflows/merge-docs.yml
- .github/workflows/rules-to-wiki.yml
- Fixes `merge-docs` failing if there is nothing new to merge (was implemented in rules to wiki, but not for this)
- See 7d98f023efdb2d1c628474f137a9f361a7af2094 and its [Action Run](https://github.com/gnembon/fabric-carpet/runs/1303970195?check_suite_focus=true)
- Adds "compatibility" with Gradle 6 in rules to wiki (see also gnembon/carpet-extra#143)
- Doesn't update this Gradle to 6, just makes the action compatible
- Also useful for any other version or change using deprecated Gradle features
> [Actions] Fix and compatibility

- src/main/java/carpet/helpers/BlockRotator.java
This basically changes the `instanceof ChainBlock` check to `PillarBlock`, since all changes used in that transformation can be applied to those. That makes cactus able to rotate any block that extends from there with a single word change.
Includes (but is probably not limited to): All logs, stripped logs, hay bales and actual pillars (and obviously chains).
> Allow flippinCactus to rotate logs, hay bales and other pillars

- .github/workflows/merge-docs.yml
This is to minify conflicts when merging PRs, I didn't think that PRs can come from main repo.
> [Actions] Only run mergedocs in master

- docs/scarpet/api/Auxiliary.md
- docs/scarpet/api/Events.md
- src/main/java/carpet/CarpetServer.java
- src/main/java/carpet/commands/ScriptCommand.java
- src/main/java/carpet/mixins/ArmorStandEntity_scarpetMarkerMixin.java
- src/main/java/carpet/script/CarpetEventServer.java
- src/main/java/carpet/script/CarpetScriptServer.java
- src/main/java/carpet/script/utils/SystemInfo.java
- src/main/java/carpet/settings/ParsedRule.java
- src/main/java/carpet/settings/Rule.java
- src/main/java/carpet/settings/SettingsManager.java
- src/main/java/carpet/settings/Validator.java
This PR adds the ability to define Scarpet apps in the `@Rule` annotation, and those will be enabled when the rule is enabled, and obviously disabled when disabled. This opens possibilities like replacing current Carpet rules or commands (like in #518) without the "hassle" for the user to change from rule to app, etc. It also mantains backwards compatibility with the rules users had before the change, allows to have both Java coded and Scarpet coded content in the same rule, and of course this also gets printed into the list of Current Available Settings and can be easily found in the `/carpet` command.
Extensions should also be able to register their own "Scarpet rules".
Working vs not working things:
Feel free to suggest more points, give feedback and/or help with some. ~~Until now, …
> Allow rules to manage Scarpet apps (Scarpet Rules)

- docs/scarpet/api/Entities.md
- src/main/java/carpet/script/value/EntityValue.java
The fourth parameter (before showParticles and showIcon) of StatusEffectInstance must be 'ambient' (which makes beacon effects less intrusive).
> Fix scarpet modify(e, 'effect', ...)

- src/main/java/carpet/network/ClientNetworkHandler.java
- src/main/java/carpet/network/ServerNetworkHandler.java
Actually fixes #546.
As I commented in that issue, rules from extension's custom `SettingsManager`s aren't synchronized with clients, they are only sent when changing a rule (as a product of calling the same method), but the client doesn't know where to place them since it only looks for the rule in Carpet's `SettingsManager`. That issue was incorrectly closed after a PR that touched a similar subject: client-side-only rules. But it wasn't fixed yet.
~This fix consists in looping through extension's custom SettingsManager's too when sending rules, and adding a namespace to them (`identifier:rule`), so the client can know where to place them. Carpet's own rules are sent without namespace to allow backwards compatibility (the client assumes a rule without namespace is from Carpet's …
> Sync extension's custom SettingsManager's rules

- docs/scarpet/api/Overview.md
- docs/scarpet/api/ScriptCommand.md
- docs/scarpet/language/Overview.md
- src/main/java/carpet/script/CarpetScriptServer.java
- src/main/java/carpet/script/bundled/FileModule.java
This is an implementation that would resolve #577.
It works as defined in https://github.com/gnembon/fabric-carpet/issues/577#issuecomment-735025354 (global scripts would basically be stored at `[root]/config/carpet/scripts`, root being either `.minecraft` or the server's root).
I've also taken the time to change some things (can revert if you want), basically changing `File` -> `Path` everywhere related to this (that is, in `listAvailableModules`, `getModule` and `FileModule`). Therefore, it instead uses Streams to do the work of finding the appropriate script or to list those. Did this because many of those methods already start with a `Path` that they convert to a `File`, require a `Path` that they convert from a `File` or even do both steps. And because you introduced me into the …
> Allow loading apps from a global path

- docs/scarpet/resources/editors/idea/2.txt
- docs/scarpet/resources/editors/npp/scarpet.xml
I almost forgot these existed (whic is embarassing, since I added them myself), but I needed them to debug the draw caching thing (to see how much of an effect it rly has) and realised it wasn't autocompleting.
> Adding convert_date and unix_time to docs

- src/main/java/carpet/helpers/OptimizedExplosion.java
Fixes gnembon#616
This is basically because in 1.16 snapshots the explosion code changed to not be eye height only for TNT.
I don't know if this fully fixes that or if it produces any other bug. I've just tested that it fixed visually (and in the end pos in the tnt logger) the specific case in the issue. I'm not an expert in explosion code. Please test.
> Fix optimizedTNT entity behaviour

- docs/scarpet/api/Events.md
- src/main/java/carpet/mixins/TradeOutputSlot_scarpetEventMixin.java
- src/main/java/carpet/script/CarpetEventServer.java
- src/main/resources/assets/carpet/scripts/event_test.sc
- src/main/resources/carpet.mixins.json
Implemented James103's suggestion #548
Added `__on_player_trades(player, entity, buy, buyB, sell)` event handler.
The parameter `entity` can be `null` if the merchant is not an entity _[in vanilla should not occur]_
> Added onTrade Scarpet Event

- src/main/java/carpet/script/value/FormattedTextValue.java
- src/main/java/carpet/script/value/Value.java
Resolves #622.
This makes the addition `+` operator correctly join two formatted text, or a formatted text first and anything else after.
~This however, doesn't allow anything `+` formatted text (reverse order), since that would make the function quite complicated (probably), and required in base `Value`. May do that at some point.~
Ok, after some time (around 20 minutes), I've decided to also add the functionality to the other side, that is: anything `+` formatted text.
```py
format('y Hello ') + format('d World') = format('y Hello ', 'd World')
format('y Hello ') + 'World' = format('y Hello ', 'w World') //# Assuming "w" as default color
format('y Hello ') + 5 = format('y Hello ', 'w 5') //# Assuming "w" as default color
'Hello '+format('d World') = format('w Hello ', 'd World' //# …
```
> Add FormattedText addition

- docs/scarpet/api/Auxiliary.md
- src/main/java/carpet/script/CarpetScriptHost.java
- src/main/java/carpet/script/api/Auxiliary.java
- src/main/java/carpet/script/bundled/FileModule.java
- src/main/java/carpet/script/bundled/Module.java
- src/main/java/carpet/script/utils/ScarpetJsonDeserializer.java
- src/main/java/carpet/script/value/AbstractListValue.java
This PR adds the ability to read and write JSON files in Scarpet.
To write them, it uses the nice, already present, `toJson` methods that were written into `Value`s. To read them, it adds logic to the new `ScarpetJsonDeserializer`, a custom deserializer for Gson.
Other minor things this changes:
- Removes hardcoded file types from the "files API". Before, everything was either `txt` or `nbt`, without using the existing `supportedTypes` map, that provides the extension for the given type. Since getting that is mostly used in `Module`, it has also been moved there
- Removes two useless usages of the old Java `File`. It was literally doing `.toFile()` on one side and `.toPath()` on the other
- Adds `Iterable<Value>` interface to `AbstractListValue`. Since it is iterable
Missing things (from …
> Reading/Writing JSON in Scarpet

- src/main/java/carpet/CarpetServer.java
- src/main/java/carpet/commands/TickCommand.java
- src/main/java/carpet/helpers/TickSpeed.java
- src/main/java/carpet/mixins/ChunkTicketManager_tickMixin.java
- src/main/java/carpet/mixins/CommandFunctionManager_tickMixin.java
- src/main/java/carpet/mixins/MinecraftClientMixin.java
- src/main/java/carpet/mixins/MinecraftServer_scarpetMixin.java
- src/main/java/carpet/network/ClientNetworkHandler.java
- src/main/java/carpet/network/ServerNetworkHandler.java
- src/main/java/carpet/script/CarpetEventServer.java
- src/main/java/carpet/script/utils/ShapesRenderer.java
_And the client_
Actually, the most important (visible) thing added from this PR is freezing the client, but Scarpet is also frozen.
This is the PR that resolves #581 and resolves #398.
_It adds new data to the Carpet Protocol to sync more features, such as frozen state and deep frozen state with Carpet clients._
Now, to the full PR:
Syncs the `is_paused`, `deepFreeze` and `super_hot` variables from `TickSpeed` with clients. With the next changes, this will allow us to freeze entity rendering, like in singleplayer, and to add client-side frozen features. The `super_hot` variable doesn't really change absolutely anything, but I added it for completeness sake to maybe try to get it working in the future (because AFAIK it does change things in SSP, doesn't it? if not, I'm dumb and that …
> ❄️ Freezing Scarpet ❄️

- src/main/java/carpet/script/language/DataStructures.java
- src/main/java/carpet/script/value/NullValue.java
Fixes an issue where `null~'string'` is searching for a substring in the actual string version of `null`, which meant that:
`null~'nu'` -> `'nu'`
`null~'l'` -> `'l'`
`null~'null'` -> `'null'`
`null~'hello'` -> `null`
Pretty sure this is not inteded, `null` represents _nothing_, and _nothing_ should not contain anything
> Fixed null acting as a string with matching operator (~) and split()

- docs/scarpet/language/Containers.md
- src/main/java/carpet/script/language/DataStructures.java
- src/main/java/carpet/script/value/ListValue.java
- src/main/java/carpet/script/value/MapValue.java
- src/main/java/carpet/script/value/NullValue.java
- src/main/java/carpet/script/value/Value.java
This PR adds the ability to `split()` to run different functions depending on the value it's trying to split.
By default, it will work as it has done until now, but this PR adds technically three (actually one) new split functions:
- Splitting a list will split it in sublists delimited by the elements which equal the delimiter
- Splitting a `null` value will return an empty list regardless of the delimiter. Until now, it would split the `null` string
- Splitting a map will throw an exception, just like `slice`
> [Suggestion] Allow splitting lists by element value

- src/main/java/carpet/script/bundled/FileModule.java
Fixes #674.
It seems ~in recent versions (snapshots)~ NbtIo.read(File) is only present in the client side, so it basically crashes the dedicated server.
This PR is more like a workaround than a full fix, that basically mimics the behaviour of that method and calls other functions that are present in both sides. Obviously finding a proper method to call instead may be desirable, but that at least works for now.
This didn't strike before because that function is only called as a fallback for simple tags, which isn't so common.
Edit: This actually also happens in the 1.16 version, thus changed the base. The branch name is therefore misleading, but was to prevent opening another PR.
> Fix NbtIo crash when loading appdata

- src/main/java/carpet/script/value/NullValue.java
This is a split of #676, adding only the ones that don't depend on the order of the operator (plus a new one).
That includes `slice()`, the one I consider the most useful of them.
| Function        | Before  | After  |
|-----------------|---------|--------|
| `slice(null,1)` | `'ull'` | `null` |
| `length(null)` | 1   | 0 |
| `-null`         | 0       | `null` |
> Extra handling of null values (split, non-order-dependant only)

- .github/workflows/publish-release.yml
- src/main/java/carpet/utils/CarpetRulePrinter.java
- src/main/java/carpet/utils/RulePrinter.java
Move it later, when the game is ready to be touched.
It previously was in pre-launch because Carpet didn't really touch the game at `onGameStarted`, now it references `Blocks` statically so it basically initializes that and makes a chain reaction until it hits a NPE. This means it'll have to wait for DFU and will take a bit more time, but it should be fine (it's been quite fast on the testrun at https://github.com/altrisi/fabric-carpet/actions/runs/537672403.
> Fix rules-to-wiki and generalize some code for extension's equivalents

- settings.gradle
JCenter is:
- Shutting down on 1st May
- Not required for anything
- Already removed from the example mod
- "Should have never been there in the first place" - modmuss50
See also: FabricMC/fabric-example-mod#78
> Remove jcenter from settings.gradle

- src/main/java/carpet/CarpetSettings.java
[MC-195640](https://bugs.mojang.com/browse/MC-195640) is "Suspicious stew inedible with full hunger", which doesn't seem right for the rule 'lightningKillsDropsFix'. The carpet rule fixes [MC-206922](https://bugs.mojang.com/browse/MC-206922) (Items dropped by mobs that were killed by lightning instantly disappear).
> Incorrect bug report for lightningKillsDropsFix

- src/main/java/carpet/script/value/EntityValue.java
Fixes #730.
No longer needs mixing, so it just uses the getter.
> Implement query(e,'fire')

- docs/scarpet/api/Entities.md
- src/main/java/carpet/script/value/EntityValue.java
`entity~'display_name'` now returns a formatted text value, which includes team colors and stylized prefixes and suffixes.
> Made entity~'display_name' return a Formatted text

- docs/scarpet/language/Containers.md
- src/main/java/carpet/script/value/ListValue.java
- src/main/java/carpet/script/value/Value.java
This fixes an issue with slice() which made it return empty strings when the upper bound was one more than the index of the last character, which should be usable for the upper bound since its non inclusive.
| Code                       | Before | Now      |
|----------------------------|--------|----------|
| `slice('abcd',3,4)`        | `''`   | `'d'`    |
| `slice('abcd',1,4)`        | `''`   | `'bcd'`  |
| `slice(split('abcd'),2,4)` | `[]`   | `[c, d]` |
Also fixed two examples of `slice()` in the docs where the upper bound was included for the example
> Fixed slice() returning empty string when referring to last character 

- src/main/java/carpet/CarpetSettings.java
- src/main/java/carpet/mixins/MinecraftServer_pingPlayerSampleLimit.java
- src/main/resources/carpet.mixins.json
The [ServerListPing Protocol](https://wiki.vg/Server_List_Ping) is used by the client when one is in the multiplayer menu. With it, the client is able to retrieve the server's player number, player limit, protocol version, favicon, and MOTD. One feature of this protocol, is the ability to retrieve a "sample" of up to twelve players currently online on the server. This information can be queried not just from the Minecraft client, but also from [external websites](https://mcsrvstat.us/) and [tools](https://andrews54757.github.io/MCObserver/) regardless of server whitelist status.
On the vanilla client, this info is displayed by hovering over the player number info, like so:
The current behavior poses two problems:
* Due to privacy concerns, not all server operators may want to broadcast …
> Add `pingPlayerListLimit` setting

- src/main/java/carpet/CarpetSettings.java
This is a "suggestion" since it could be considered a workaround, and may not be the preferred method to do this.
This basically removes the `COMMAND` category from `commandScriptACE` to prevent app malfunction in a locked SettingsManager, since every `COMMAND` rule is disabled unless explicitly stated, making apps run commands with permission level `0`.
I think it shouldn't be a problem to not turn it down, since apps can already do most of the things commands are doing with native functions, and command level 2 isn't giving them anything that could make things go wrong.
Doing that also fixes a small documentation mismatch, since else it said that it had an accompanying command.
Resolves #734, fixes gnembon/scarpet#180 and closes gnembon/scarpet#183.
At the same time I fixed the bug I …
> Fix `run()` with a locked SettingsManager

- src/main/java/carpet/script/CarpetScriptServer.java
Theoretically fixes #749.
`Files#exists` does follow symbolic links, so there should be no problem in calling `Files#createDirectories` after that is checked to be false.
Also allows the global script `walk` function to follow symlinks.
Note that I haven't really tested this, since I don't currently know how to make symlinks on Windows, but at least it shouldn't break anything.
> Fix symbolic links in app load

- docs/scarpet/api/Auxiliary.md
- docs/scarpet/api/BlocksAndWorldAccess.md
- docs/scarpet/api/Inventories.md
- docs/scarpet/api/Scoreboard.md
- docs/scarpet/language/FunctionsAndControlFlow.md
- src/main/java/carpet/script/Expression.java
- src/main/java/carpet/script/api/Auxiliary.java
- src/main/java/carpet/script/api/Inventories.java
- src/main/java/carpet/script/api/Scoreboards.java
- src/main/java/carpet/script/api/WorldAccess.java
- src/main/java/carpet/script/exception/ExpressionException.java
- src/main/java/carpet/script/exception/InternalExpressionException.java
- src/main/java/carpet/script/exception/ProcessedThrowStatement.java
- src/main/java/carpet/script/exception/ThrowStatement.java
- src/main/java/carpet/script/exception/Throwables.java
- src/main/java/carpet/script/language/ControlFlow.java
- src/main/java/carpet/script/utils/ShapeDispatcher.java
- src/main/java/carpet/script/value/BlockValue.java
- src/main/java/carpet/script/value/FunctionValue.java
- src/main/java/carpet/script/value/NBTSerializableValue.java
- src/main/java/carpet/script/value/ValueConversions.java
Since mods (or even resource/data/whatever packs) can add many things that Scarpet can opt to read, and just returning `null` may not be ideal in many cases, this PR allows some, specified exceptions to be caught. Not every exception is catchable, mostly to prevent people just wrapping everything in a big `try` block. At the same time this PR it also overhauls the current exception system a bit.
What's that overhaul?
Now exceptions have two different values: Their "id" and their message. The id is something that should be kind-of general, in order to allow apps to easily filter exceptions in the code. The message is, well, the message that will be shown in the stacktrace when being unhandled. The id is present in the old `_` variable, and in order to make the message useful, it is passed …
> Exception handling features

- docs/scarpet/api/Scoreboard.md
- docs/scarpet/resources/editors/idea/2.txt
- docs/scarpet/resources/editors/npp/scarpet.xml
- src/main/java/carpet/script/api/Scoreboards.java
Fixes #731 
Resolves #672 
Adding `scoreboard_property` to change and read various properties of scoreboard objectives:
`scoreboard_property(objective, property)`
`scoreboard_property(objective, property, value)`
* `criterion`
* `display_name` (Formatted text supported)
* `display_slot`: When reading, returns list of slots, when modifying, displays the objective in the specified slot
* `rendertype`: Either `'integer'` or `'hearts'`, defaults to `'integer'` if invalid value specified
* `remove`: Removes the objective, specifying a `value` doesn't matter
This deprecates the part of `scoreboard_add` which allowed changing scoreboard criterions. 
The `scoreboard_remove` function is also deprecated. The two parts of `scoreboard_remove` were:
* Removing an objective. This is now done with …
> Optimizing scoreboard API with scoreboard_property

- src/main/java/carpet/mixins/CommandManagerMixin.java
Allows the command stacktrace mixin to soft fail to allow for better compatibility with with other mods that try to do the same thing. I think it's a good idea to make it optional in Carpet since it's possible that other mods that don't care about Vanilla behaviour will replace it straight up with `true`, therefore not behaving as expected when Carpet is present because of not knowing about secret settings. After all, I guess the command stacktrace, given it being in secret settings, is not the most important thing for end users, and when debugging there probably won't be anything touching it.
Fixes #765 in many situations, though theoretically not in 100% of the cases because of the arbitrary mod loading order (not really tested, but at least in the specific issue case should be fixed). …
> Make command stacktrace mixin not required

- src/main/java/carpet/script/exception/ExpressionException.java
Makes `ExpressionException`'s second smallest constructor call the next with default params instead of filling the thing itself.
Would also love to get rid of the independence (or) of one of the other two, didn't do because of the two options I had:
- Drop the one with the Supplier: It is currently only used when instantiating processed throw statements to (I guess) make them not call `getString()` on construction (since they can still be caught). Can it be that expensive?
- Make the non-supplier constructor create a supplier with the passed message. Would keep the supplier for throwables and would still make all constructors rely on one after all.
- (new) Making the last constructor's supplier be the lazyMessage supplier and making the non-supplier version and the throwable create it. …
> Chain an exception's constructor

- docs/scarpet/api/Auxiliary.md
- docs/scarpet/api/BlocksAndWorldAccess.md
- docs/scarpet/language/LoopsAndHigherOrderFunctions.md
- docs/scarpet/language/Operators.md
Added in scapet docs an example for recipes and for loot tables.
Fix #795
> More datapack examples

- src/main/java/carpet/CarpetSettings.java
- src/main/java/carpet/mixins/FluidBlock_renewableDeepslateMixin.java
- src/main/java/carpet/mixins/LavaFluid_renewableDeepslateMixin.java
- src/main/resources/carpet.mixins.json
Fixes #767 
Adds new rule `renewableDeepslate`
Instead of stone and cobblestone, deepslate and cobbled deepslate will generate from water and lava below y-level 0.
Wasn't sure if i should combine the `FluidBlock_renewableDeepslateMixin` with the already existing `FluidBlock_renewableBlackstonMixin`, or leave them seperate since they are different rules. If they should be combined, what name would the mixin get?
> Added renewableDeepslate

- docs/scarpet/api/Auxiliary.md
- docs/scarpet/api/Overview.md
- src/main/java/carpet/script/CarpetScriptHost.java
- src/main/java/carpet/script/CarpetScriptServer.java
- src/main/java/carpet/script/utils/SystemInfo.java
Note: Doesn't have docs since I'm not really sure where to specify this/I was too lazy to check (at least yet, feel free to add them).
Resolves #644.
Allows Scarpet apps to specify dependencies on mods, including specific mod versions (using a `>=` comparison).
Syntax is basically the following:
```py
__config() -> {
'requires' -> {
'carpet' -> '1.2.3',
'minecraft' -> '1.16',
'java' -> 11,
'carpet-extra' -> '*',
...
},
...
};
```
That means: `Carpet at least 1.2.3, Minecraft at least 1.16, Java at least 11, any Carpet Extra version`.
This basically supports requiring any arbitrary mod to be present, since it uses FLoader's (not FAPI) APIs to get whether the mod is present and what version is it running, plus parsing the requirement as a semantic version and comparing it properly. …
> Allow apps to specify mod version requirements

- docs/scarpet/api/Auxiliary.md
- src/main/java/carpet/CarpetServer.java
- src/main/java/carpet/logging/HUDController.java
- src/main/java/carpet/script/api/Auxiliary.java
Implements (and GH keyword) Closes #818.
This PR changes the `display_title()` signature for things in the `player_list` to `display_title(targets, position, text)`, making it the same as the other `display_title()` arguments.
Not only that, it also changes the internals so that those headers and footers are stored in `HUDController` instead of just being sent once. HUDController will then make sure that those values are sent to the client even if it's sending other loggers at the same time.
Current behaviour is to display the Scarpet footer above loggers, can easily be changed by moving the call it has in `HUDController#updateHud`.
`CarpetServer` will reset the Scarpet headers and footers when the world changes, but they will be stored for the player while the server is running (if SPE …
> Make `player_list` take arguments one at a time and make it compatible with loggers

- src/main/java/carpet/logging/HUDController.java
This method should be static, isn't it? I don't think there's a reason for not having the `static`, since it's wired for extensions to instantiate a `HUDController` object to register a hud listener
https://github.com/gnembon/fabric-carpet/blob/8ed4c60b9c321860932b629e7fcd987b61111d30/src/main/java/carpet/logging/HUDController.java#L35-L42
> Fixed missing static keyword at method HUDController.register

- src/main/java/carpet/script/api/Auxiliary.java
- src/main/java/carpet/script/api/Scoreboards.java
- src/main/java/carpet/script/value/EntityValue.java
- src/main/java/carpet/script/value/FormattedTextValue.java
I noticed there are a lot of instances where there is a `value instanceof FormattedTextValue` check, so this static method in the `FormattedTextValue` class replaces all of those.
In the EntityValue modifying customName code, i also swapped the LiteralText constructor with this, which makes it possible to use formatted text here too, useful side effect.
> Adding getTextByValue method to replace duplicate code

- src/main/java/carpet/script/value/NBTSerializableValue.java
Resolves #746.
Basically that. If the requested address ends with `[]` it will create either a singleton with the element.
PENDING TESTING
Can this break apps relying on the old functionality?
I guess maybe? But most should work since the check that seems to be done usually is to convert it to a list if it's not, and this will just return lists in more cases. And it still returns null for no items.
> Make `get()` always return a list if requested item ends with `[]`

- src/main/java/carpet/script/value/FormattedTextValue.java
Fixed formatted texts sometimes being false as boolean, even if it contains text.
`bool(format('db test'))` used to return false, now it returns true
Another side effect is that the display_title header/footer didnt work with a formatted text, since it checks for the boolean value and clears them if false.
This was introduced in e26e332a6d319cd818f8c8d29f4dc20ca9a0d238
When testing it a bit now, asString returned an empty string in some cases, with text contained in the FormattedText value (not just a empty, but formatted string)
Apparently getString works, not sure why that would be different though
> Fixed boolean value of FormattedText being incorrect

- docs/scarpet/api/Auxiliary.md
- docs/scarpet/api/BlocksAndWorldAccess.md
- docs/scarpet/api/Entities.md
- docs/scarpet/language/Containers.md
- docs/scarpet/language/FunctionsAndControlFlow.md
- docs/scarpet/language/LoopsAndHigherOrderFunctions.md
- docs/scarpet/language/Math.md
- docs/scarpet/language/Operators.md
- docs/scarpet/language/Overview.md
- docs/scarpet/language/SystemFunctions.md
Replacing all cases where `l()` is still used for constructing lists with `[]`, exept of course those that explain the function version of it.
Thought this was needed since in 25f5a3771ded7a2bd27019a6cc88d59c6b327330 the `l()` got changed too, and i noticed the other modify() lists were also still `l()` so i searched through all docs and replaced it
> Switch out l() syntax to [] in docs

- src/main/java/carpet/settings/ParsedRule.java
That was a thing of mine when fixing `getBoolValue` for Scarpet rules.
This new way removes the set in favour of using Apache's ClassUtils `primitiveToWrapper` method, which gets the wrapper class, that actually extends `Number`.
Technically fixes rules (from extensions maybe?) using wrappers as their numbers. However other parts checking specifically for primitives aren't changed (e.g. checks for `boolean.class`) (would it be worth setting `type` to the wrapper and only check equality with wrappers? Not sure)
> Remove the number_classes set in favour of ClassUtils

- src/main/java/carpet/script/CarpetScriptHost.java
- src/main/java/carpet/script/CarpetScriptServer.java
- src/main/java/carpet/script/api/WorldAccess.java
A bit more compact and prevents autoboxing. Was mostly bored.
Also (completely unrelated to this PR), Carpet for releases could still be built using Loom 0.7, since that's supposedly more stable and has support for building using Java 8 through 16 (rn Carpet requires Java 16 to be built since Loom 0.8 targets it).
Edit: `test.test()` may not be the most expressive name for the function, yeah, but at that time I just changed the types.
> Use primitive specific Predicate instead of Boolean Function

- src/main/java/carpet/script/value/EntityValue.java
- src/main/java/carpet/script/value/NumericValue.java
Title.
Resolves #879.
Changes `NumericValue` to hold a primitive double, I guess should help with heavy loads with numbers by avoiding autoboxing and autounboxing (there were no `null` checks or assignations to that variable) (haven't tested it, at least yet, just no compile errors).
> Use primitive doubles in `NumericValue` and allow adding exhaustion with floats

- src/main/java/carpet/script/CarpetEventServer.java
- src/main/java/carpet/script/api/Auxiliary.java
- src/main/java/carpet/script/api/Inventories.java
- src/main/java/carpet/script/api/Scoreboards.java
- src/main/java/carpet/script/api/WorldAccess.java
- src/main/java/carpet/script/command/CommandArgument.java
- src/main/java/carpet/script/language/DataStructures.java
- src/main/java/carpet/script/language/Threading.java
- src/main/java/carpet/script/utils/ShapeDispatcher.java
- src/main/java/carpet/script/utils/SystemInfo.java
- src/main/java/carpet/script/value/BooleanValue.java
- src/main/java/carpet/script/value/EntityValue.java
- src/main/java/carpet/script/value/NumericValue.java
- src/main/java/carpet/script/value/ValueConversions.java
Shouldn't change behaviour since `BooleanValue` extends `NumericValue`.
I'm currently in the process of finding whether other extensions are using the constructor in order to make it protected (for boolean and null constructors) instead of deprecated (couldn't those use the numeric constructor with `0`?).
Update: Used by Carpet TIS Addition
> Deprecate old boolean constructor and move existing usages

- src/main/java/carpet/script/CarpetEventServer.java
- src/main/java/carpet/script/value/EntityValue.java
- src/main/java/carpet/script/value/ListValue.java
It has been deprecated since over 6 months ago (9e8556f9d9504651df0022a57edddd2487dcb48b). Couldn't really find any usage outside of Carpet.
> Replace usages of deprecated ListValue::fromItemStack and remove it

- src/main/java/carpet/script/annotation/AnnotationParser.java
- src/main/java/carpet/script/annotation/Param.java
- src/main/java/carpet/script/annotation/ScarpetFunction.java
What was I thinking? Not sure.
Allows reusing the methods in there without needing a stupid instance. Still allows non-static methods.
```java
new ScarpetFunctions().do_something(); /* -> */ ScarpetFunctions.do_something();
```
Also makes minor changes to javadoc, makes two "registries" final, and removes the old, commented out `LazyValue` provider.
> Allow static methods for Scarpet Functions

- src/main/java/carpet/script/annotation/Locator.java
- src/main/java/carpet/script/argument/BlockArgument.java
Does so by making the end function use an iterator, that for current functions comes from a `params.listIterator(offset)` call in order to keep current Scarpet functions working.
Small note: `BlockArgument.findInValues(...)` seems to do exactly the same as `findIn` (assuming it's from before the lazy refactor). I think it could be dropped. Edit: Nothing seems to call it.
About the other locators: I don't really know how to implement them (at least yet) since they require list length, which an iterator can't provide.
> Implement `@Locator.Block`

- src/main/java/carpet/script/annotation/Locator.java
- src/main/java/carpet/script/argument/FunctionArgument.java
- src/main/java/carpet/script/argument/Vector3Argument.java
By basically consuming the whole iterator, since that's what the locator was going to do anyway.
Small thing: Isn't the `offset` value of LocatorArgument incorrect in case of varargs? It isn't really used anyway since everything is consumed and passed to the args, but just mentioning.
Easier than expected, just had to change the size check for an `iterator.hasNext()`, since it's in the exact position.
> Implement `@Locator.Function` and `@Locator.Vec3d`

- src/main/java/carpet/mixins/CrashReport_addScarpetAppsMixin.java
- src/main/resources/carpet.mixins.json
At least until all those crashes caused by Scarpet apps are fixed.
Uses the same mixin as `fabric-crash-report-info-v1` in order to do so.
Only adds the section if the `scriptServer` is not null and if there are apps loaded.
<details>
<summary>Example crash (no FAPI, therefore no modlist)</summary>
```
...
-- System Details --
Details:
Minecraft Version: 1.16.5
Minecraft Version ID: 1.16.5
Operating System: Windows 10 (amd64) version 10.0
Java Version: 16.0.1, AdoptOpenJDK
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
Memory: 311382680 bytes (296 MB) / 563085312 bytes (537 MB) up to 2116026368 bytes (2018 MB)
CPUs: 8
JVM Flags: 1 total; -XX:+ShowCodeDetailsInExceptionMessages
Loaded Scarpet Apps: 
world-edit
cam
Player Count: 0 / 20; []
Data Packs: vanilla …
```
> Add a crash report section for Scarpet apps

- src/main/java/carpet/script/annotation/ValueConverter.java
Oops, my bad.
Had only tested `Value` directly for that small branch of the code. Now it does work.
(NumericValue, etc wouldn't check in ValueCaster but fall below, throwing)
> Fix Value detection in ValueConverter selection 

- src/main/java/carpet/CarpetServer.java
- src/main/resources/fabric.mod.json
Completely subjective, feel free to close it.
I just thought it was using too much space, and decided to convert it into a handle stored in a field instead. Also makes `CarpetServer` not implement those interfaces directly.
> Compact fabric initialization code

- src/main/java/carpet/script/argument/FileArgument.java
This PR completely gets rid of `File` usages in Scarpet file managing to use nio's Path instead (to hopefully help in more complicated file systems), and also adds logging to IOExceptions that occur in those cases, so it's easier to see what's going on (will help with issues like #919, already resolved that one).
> A bit more nio and log IO errors

- src/main/java/carpet/CarpetSettings.java
- src/main/java/carpet/mixins/RedstoneWireBlockMixin.java
This PR re-introduces the `fastRedstoneDust` optimization in 1.16.5+ that seems to have been removed after the changes to redstone dust in snapshot 20w18a.
My assumption for the removal of this optimization was due to the changes of the vanilla redstone wire code. These changes did not seem as significant as they appeared to be as they consisted primarily of code reorganization. I reworked the `RedstoneWireBlockMixin` class around these changes so that it functions in the same way as the previous successful implementation while keeping the changes to a minimum.
Any feedback is greatly appreciated, and hopefully we can get this optimization back into the Carpet mod!
> Re-implement `fastRedstoneDust` Optimization in 1.16.5+

- src/main/java/carpet/CarpetSettings.java
- src/main/java/carpet/mixins/FluidBlock_renewableDeepslateMixin.java
- src/main/java/carpet/mixins/LavaFluid_renewableDeepslateMixin.java
Instead of only generating below y0, deepslate generates below y16 (where deepslate blobs are found too)
This is to make renewable deepslate work in standard 1.17 worlds as well, without extended world height below y0
> Made deepslate generate below y16

- src/main/java/carpet/script/utils/AppStoreManager.java
Fixes #957.
This PR makes the suggestion builder of the `/script download` command filter the suggestions according to the player's input. The reason it's a bit more complex than just stream & filter is to "open" and suggest directory contents when only a single folder is left after the filtering.
> Filter script download suggestions according to player input

- src/main/java/carpet/CarpetSettings.java
Those were strict, and it seems like `double` strict rules can be set, but not loaded (they print invalid and skip them).
This fixes that bug, but the behaviour from config read and rule set should probably unified at some point.
> Fix creativeFlyDrag and creativeFlySpeed not loading from config

- docs/scarpet/api/Overview.md
Resolves #967.
It's a quite useful argument type actually, used in some built-in apps too. It is even used in an example.
> Document `entities` argument type

- docs/scarpet/api/Overview.md
- docs/scarpet/language/FunctionsAndControlFlow.md
- src/main/java/carpet/commands/ScriptCommand.java
- src/main/java/carpet/script/CarpetScriptHost.java
- src/main/java/carpet/script/utils/AppStoreManager.java
Fixes #954.
This PR changes how the `type` argument is used for and allows properly loading apps and libraries when requested resource is of `app` type.
The `type` property is changed to instead of reflecting whether the path is relative, absolute or a full url with (IMO) misleading names, reflect whether you are requesting a regular file or another app/library. In order to determine the type of path, I added a new method (`getFullContentUrl`) that checks whether the path starts with `http(s)://` (then URL), starts with `/` (then absolute path) or none of the previous ones (relative path). In order to keep possible older apps working, `type -> store` is kept but deprecated to create absolute paths from otherwise relative ones. `type` is no longer mandatory.
The loading of apps and …
> Change how resource `type` works, allow proper app and library installation

- src/main/java/carpet/helpers/OptimizedExplosion.java
- src/main/java/carpet/logging/logHelpers/ExplosionLogHelper.java
- src/main/java/carpet/script/api/Inventories.java
- src/main/java/carpet/script/language/Functions.java
- src/main/java/carpet/script/language/Sys.java
- src/main/java/carpet/script/value/EntityValue.java
- src/main/java/carpet/script/value/NumericValue.java
- src/main/java/carpet/script/value/ValueConversions.java
Another newer Java feature.
I've checked every non-mixin class with `instanceof` and changed those that immediately assigned a variable with a cast, other than those (one) that I thought hurt readability. Didn't touch those that only cast the existing variable later to pass it/invoke something on it, since that would add an extra field allocation etc.
Lightly tested, but shouldn't break.
> Use pattern matching for instanceof

- src/main/java/carpet/CarpetSettings.java
- src/main/java/carpet/mixins/CoralBlockMixin.java
- src/main/java/carpet/mixins/CoralFanBlockMixin.java
- src/main/resources/carpet.mixins.json
allows you to switch between disabled, coral_only, fan_only and enabled-mode to allow you to also disable/enable growing corals from coral-fans to make them easier to farm.
> added more customizability to renewableCoral

- src/main/java/carpet/script/api/WorldAccess.java
Resolves #1086.
The interaction manager and the method is (at least now) public, and I compared them and they were the same, so I assumed it would be safe to just use it directly, so also if in an update the method is changed, there is no discrepancy with vanilla.
Should I keep the comment and move it right above the line where the method is called?
> Use `player.interactionManager.tryBreakBlock` instead of a copy to be more compatible

- src/main/java/carpet/mixins/ServerPlayerEntityMixin.java
- src/main/java/carpet/mixins/StructureFeatureMixin.java
- src/main/java/carpet/script/CarpetEventServer.java
- src/main/java/carpet/script/Expression.java
- src/main/java/carpet/script/value/Value.java
- src/main/java/carpet/settings/SettingsManager.java
- src/main/java/carpet/utils/SpawnReporter.java
Makes exceptions report their stack traces through the Carpet logger.
Else Java prints them to `System.out` (or `System.err`, not sure), which is replaced by the game and doesn't handle it as an exception, but prints every single line separately and makes a bit of a mess.
> Report exception stack traces through the logger

- src/main/java/carpet/fakes/ThreadedAnvilChunkStorageInterface.java
- src/main/java/carpet/mixins/ServerChunkManager_tickMixin.java
- src/main/java/carpet/mixins/ThreadedAnvilChunkStorage_scarpetChunkCreationMixin.java
Simple rename.
This occurs because getChunks is a method of TACS (ChunkMap) in mojmap, and mixin by default overwrites whatever it finds, and it actually calls the same method, so it ends up being a recursive call until there's a StackOverflow.
> Fix Stack Overflow in development environment with mojmap

- src/main/java/carpet/CarpetSettings.java
- src/main/java/carpet/helpers/ThrowableSuppression.java
- src/main/java/carpet/logging/LoggerRegistry.java
- src/main/java/carpet/mixins/MinecraftServer_updateSuppressionCrashFixMixin.java
- src/main/java/carpet/mixins/ServerPlayerEntity_updateSuppressionCrashFixMixin.java
- src/main/java/carpet/mixins/World_updateSuppressionCrashFixMixin.java
- src/main/resources/carpet.mixins.json
Ported rule `updateSuppressionCrashFix` from Carpet-Extra
Also added catch for update suppression in neighbor update during ServerPlayerEntity tick (soulbound chest crash)
Added Logger `updateSuppressedCrashes` so not everyone sees the crash messages
Added Coords to crash message so we now know where it originates from
> Ported rule `updateSuppressionCrashFix` from Carpet-Extra + More

- src/main/java/carpet/commands/LogCommand.java
- src/main/java/carpet/logging/HUDLogger.java
- src/main/java/carpet/logging/Logger.java
- src/main/java/carpet/logging/LoggerRegistry.java
Fixed a small bug I noticed when working with the explosion logger. Putting in an invalid option is not caught by carpet mod. Basically you could run the command /log explosions invalid (where invalid can be any random string) and it would allow that. When it logs an explosions, the logger would just output the tick but no actual info about the explosion. All I did was add a check to the LogCommand.java class which checks if the given option is a valid option or not.
> fixed logger option bug

- src/main/java/carpet/helpers/OptimizedExplosion.java
Instead of caching 2 BlockState HashMaps, this uses 1 HashMap for BlockState and 1 HashMap for blast resistance, meaning that more calculations are cached, using only the necessarry ones. Also doesn't try to blow up air.
> Optimize explosion BlockState caching

- src/main/java/carpet/commands/TickCommand.java
The current implementation only allows toggling tick freeze, so scripting is hard. This patch enables users to specifically freeze or unfreeze other than just toggling. It also provides `/tick freeze status` command to dynamically check whether the game is frozen or not.
This patch preserves compatibility to the existing `/tick freeze` toggle command.
> support '/tick freeze on', '/tick freeze off' and '/tick freeze status'

- src/main/java/carpet/settings/SettingsManager.java
Search in substrings only if no rule name starts with the query string, to prevent receiving too many suggestion even if you entered the command precisely
As discussed in carpet mod discord https://discord.com/channels/882822986795716608/882831843165085758/900731726458945536
The logic is shown as follow example:
> Smart rule name auto-completion

- src/main/java/carpet/script/CarpetScriptHost.java
- src/main/java/carpet/script/ScriptHost.java
- src/main/java/carpet/script/exception/ExpressionException.java
Resolves #1051.
This PR adds a hover over tooltip for references to locals in the exception's stacktrace. It does so by trying to find the variables in the Strings directly, so there can be false positives (though _many_ of those that cause actual variables to not be available should be handled by the logic).
Things I'm not sure about: Should ErrorSnooper instead ask for the entire `ExpressionException`, since it uses most of it anyway? Should the color of the tooltip be changed to gray (or some other color)? Should the `evalValue` for locals be inside a try-catch in case there's a possibility for another exception to be thrown in there?
> Make ErrorSnooper report values for locals in the stacktrace

- docs/scarpet/api/Auxiliary.md
- src/main/java/carpet/script/utils/SystemInfo.java
Adds `world_min_y` and `world_max_y` to `system_info`. Rn only works in caller dimension, though I bet there's a way to get around that.
> Adding min_y, max_y and world_border_info to system_info

- src/main/java/carpet/mixins/NoiseColumnSamplerMixin_scarpetMixin.java
hi - caveEntrance noise was previously being checked incorrectly (it was scaled up by 4x when it should actually just use world pos.) This should fix it, but I haven't tested it (to verify, stand in a cave entrance and do /script run sample_noise(x,y,z,'caveEntrance'). If it returns less than 0, the value is accurate.
> Fix caveEntrance sampling being incorrect (please check)

- src/main/java/carpet/script/value/ThreadValue.java
This refactors the constructor of `ThreadValue`, in order to allow extending it in extensions more easily. As an example, in Discarpet I am hoping to use scarpet tasks as the return value of functions that run API calls, and as such, they take a while to finish and return a value. (https://github.com/replaceitem/carpet-discarpet/issues/18#issuecomment-986299250) However, the current constructor only allows for the creation of tasks from `FunctionValue`s.
> [Scarpet] Task value refactor for better extendability

- docs/scarpet/Full.md
- docs/scarpet/api/Entities.md
- docs/scarpet/language/Operators.md
`query(p, 'holds', 'main')` is invalid.
`query(p, 'holds', 'mainhand')` is the correct format currently.
> Minor Docs update

- src/main/java/carpet/script/Expression.java
- src/main/java/carpet/script/Fluff.java
- src/main/java/carpet/script/annotation/AnnotationParser.java
- src/main/java/carpet/script/annotation/ScarpetFunction.java
- src/main/java/carpet/script/annotation/ValueConverter.java
Resolves #1231.
This PR makes minor improvements to the annotation API, such as printing the usage on fixed param functions, removing some magic numbers in favour of constants and minor javadoc changes. It also fixes a bug disallowing unlimited parameter functions.
This will have one small conflict with future, given Crec already made the fix for unlimited parameter functions there. However, that one didn't have the change to constants instead of the magic `-1`.
> Minor improvements to scarpet annotation API

- src/main/java/carpet/script/api/Entities.java
Fixes #1163.
Own tests confirm that this implementation is faster than `entity_selector('@a')`. Not by much, but faster regardless, and definitely faster than the previous implementation.
In order to accomplish this, this PR:
- Removes streams completely. The overhead of streams is what was likely causing the big performance difference
- Removes case-insensitive comparisons. The method was never documented to accept different casing and it is more expensive (and bulkier) than a regular comparison.
At the same time changes the big if-else chain into a switch statement, that should also improve performance for the rest of cases because (I believe, not 100% sure) it uses a hash table internally and should be able to pick a branch directly.
> Improve performance of `player()` related methods

- docs/scarpet/api/Auxiliary.md
- src/main/java/carpet/utils/Messenger.java
Resolves #1182.
This PR adds the following two actions to `Messenger` (and therefore to the scarpet's `format()` function):
- `'@<url>'` Opens the given url when clicking the message
- `'&<text>'` Copies the given text to clipboard when clicking the message
Also changed it to use a switch statement and made some small changes to conventions in the rest of Messenger (where they didn't affect api).
> Support more actions in Messenger (and therefore `format()`)

- gradle.properties
- src/main/java/carpet/script/CarpetScriptHost.java
- src/main/java/carpet/script/CarpetScriptServer.java
- src/main/java/carpet/script/exception/LoadException.java
- src/main/resources/fabric.mod.json
Fixes #1042.
- App `requires` now also supports x-ranges, for example things like `1.17.x` (or whatever they're called)
- Carpet now requires Fabric Loader 0.12.8 or newer
This PR changes the way dependency resolution for scarpet apps is done to use the newly exposed implementation in loader (was made public API in loader 0.12.3, the minimum required version has been set to 0.12.8 since 0.12 was beta until .6 and .7 also had some small bugs). That simplifies the code on the carpet side by _a lot_ and allows the use of x-ranges in version dependencies other than just the old operators.
Not only that, the PR also fixes #1042 by introducing a new exception type, `LoadException`, that can be thrown during app loading and will travel up the stack until the creation of the app and will cancel …
> Use Fabric's implementation for app load mod requirements and change its messaging

- src/main/java/carpet/commands/PlayerCommand.java
Fixes #1263 
Basically if you're in spectator (or creative for that matter), spawning a fake player in survival or adventure mode would cause that player to have flying abilities.
> Fake players can be spawned in survival mode while flying

- src/main/java/carpet/script/api/Auxiliary.java
Fixes #1262.
My bad, forgot the prefix.
> Fix deprecated `last_tick_times`

- src/main/java/carpet/CarpetSettings.java
- src/main/java/carpet/mixins/AbstractCauldronBlock_stackableSBoxesMixin.java
- src/main/java/carpet/mixins/ItemEntityMixin.java
- src/main/java/carpet/mixins/ScreenHandler_stackableSBoxesMixin.java
- src/main/java/carpet/mixins/Slot_stackableSBoxesMixin.java
- src/main/java/carpet/settings/SettingsManager.java
This is to help balance this feature a bit. Also makes a bit more sense to have shulker boxes to stack to 16 instead of 64 since Minecraft has already established (see: bucket) that empty stuff can only stack to 16. Anyway this just allows it to be configurable.
The old stackableShulkerBoxes rule has been removed and replaced with simply using the value "1" as the stack size for shulker boxes. It's up to you if this is how you want to implement it, I think it makes the most sense to have it as the one option but people might prefer having two separate options, one for stack size and one for whether they stack at all. 
With my implementation, the configuration will simply default to 1, which is basically "off" like before and no calculations will be attempted until the value exceeds 1.
> Shulker box stack size is now configurable

- src/main/java/carpet/mixins/Entity_scarpetEventsMixin.java
Fixes #1282 
It's basically a check for whether or not the position changed. Idk if there's a neater way to put it tho tbh.
> Fixed firing of on_move event event after no change in position.

- build.gradle
- settings.gradle
Simply adds [loom quiltflower](https://github.com/Juuxel/LoomQuiltflower) as a plugin which adds `genSourcesWithQuiltflower`.
This task uses [quiltflower](https://github.com/QuiltMC/quiltflower) to decompile sources which is an improved fork of original fernflower developed by [QuiltMC](https://github.com/QuiltMC) team
Run `genSourcesWithQuiltflower` task instead of `genSources`
> Add quiltflower

- src/main/java/carpet/script/utils/AppStoreManager.java
The validator used to clear the sealed flag and the children in the validator. But it did not clear the count down latch. This led to a situation where we would throw an IOException from fillChildren because we did have the latch, but it was zero, and the sealed flag was cleared. This simply resets the node every time, which I think is the safest solution as setting the childrenProgress to null in the validator might end poorly if someone was waiting on it. Another solution was to just remove the throw inside fillChildren. This felt like the cleanest solution.
> Always reset the app store root in the validator (#1275).

- src/main/java/carpet/script/annotation/AnnotationParser.java
- src/main/java/carpet/script/annotation/SimpleTypeConverter.java
- src/main/java/carpet/script/annotation/ValueCaster.java
Changes in this PR:
- Changed `valueConverters` List to array for faster access
- Remove duped param size check when scarpet argument count isn't variable, as it's already checked by LazyFunction
- Remove invocations of `Class.cast` and use direct casts instead
The last point adds the need for two `SuppressWarning` annotations. However, the change is needed because even with `Class.cast` being intrinsic, neither javac or the jvm knows they can get rid of it, and javac even adds more casts to the method. Doing it this way, the compiler even assumes the (T) cast is safe and removes it.
This was needed because checking the inlining log, I was amazed after seeing that `SimpleTypeConverter#convert` was hot but "too big to be inlined", and I dug for the reason.
I haven't checked much more, but …
> Improve Annotated Scarpet runtime performance

- src/main/java/carpet/mixins/LivingEntity_maxCollisionsMixin.java
Improve compatibility with mods that manipulate how cramming works. When the carpet rule is disabled, the vanilla code can be used, allowing features from other mods to work.
> Use vanilla cramming code when possible

- src/main/java/carpet/CarpetSettings.java
- src/main/java/carpet/mixins/ChunkMap_creativePlayersLoadChunksMixin.java
- src/main/resources/carpet.mixins.json
enabled by default: behavior like vanilla
disabled: creative players do not load chunks like spectators with gamerule spectatorsGenerateChunks false
> new: creativePlayersLoadChunks carpet rule

- src/main/java/carpet/script/api/WorldAccess.java
- src/main/java/carpet/script/value/BlockValue.java
Fixed an issue reported in Discord where an exception would be thrown in those cases.
The unimplemented method was going back to try to use the player (that isn't passed), throwing a NPE with items like pointed dripstone, and the painting fix is because it relies in the context being horizontal already without asking the context via the horizontal method, therefore we now change the default to a horizontal direction if it's a painting. The direction isn't changed if the user did specify a direction.
With this, a loop through all items completes without those exceptions.
PS: The method was added in 1.17 if I used fabric bot correctly for that.
> Fix exceptions in `place_item` by implementing a missing method in PlacementContext and special case paintings

- docs/scarpet/Full.md
- docs/scarpet/api/Entities.md
Adds a few values from `src/main/java/carpet/script/value/EntityValue.java` that were missing in the documentation. Also, fixes some typos.
> Missing EntityValue documentation

- docs/scarpet/api/Events.md
- docs/scarpet/resources/editors/idea/4.txt
- docs/scarpet/resources/editors/npp/scarpet.xml
- src/main/java/carpet/mixins/ServerGamePacketListenerImpl_scarpetEventsMixin.java
- src/main/java/carpet/script/CarpetEventServer.java
- src/main/resources/assets/carpet/scripts/event_test.sc
Adds an `__on_player_message(player,message)` event, which triggers when a player sends a chat message or runs a command.
This is part of #937, and the interception part will be achievable when event cancellation is a thing.
> Added __on_player_message event

- src/main/java/carpet/script/Fluff.java
When the optimizer is on, running those operators during the optimization phase in a way they throw `InternalExpressionException` will cause the exception to be leaked outside of the scarpet stack, returning "unexpected error while running command" or crashing the game.
The issue is caused because their try-catch blocks were placed when creating the lambda, not when executing them.
Given the exceptions don't get leaked during regular execution (outside the optimizer), this makes me feel like there's unnecessary try-catch blocks in regular execution somewhere, but I don't know enough of the inner workings of Scarpet to analyse it or be confident about removing any.
Reproducers that trigger this issue:
- `-[]`
- `'a' % 2`
> Fix unhandled exceptions when evaluating operators

- jitpack.yml
Jitpack uses java8 by default and obviously that doesn't work for MC 1.17+ development. We need java17 to make jitpack work and what we need is just a jitpack config file (https://docs.jitpack.io/building/#java-version)
With this PR, mod devs don't need to wait until carpet publishing to masa's maven to test their extensions with the latest carpet
It's also useful when testing the PR branches since the `jitpack.yml` will be in those PR branches too
> Added jitpack support

- src/main/java/carpet/CarpetServer.java
This PR makes Carpet print a warning if extensions register themselves late, with the idea of (maybe) later making that throw an exception and later just not have the fallback if they register late.
There's multiple methods extensions can use to register themselves in time, they should make sure they are registering correctly IMO and Carpet shouldn't be checking that.
> Print a warning when an extension registers late

- docs/scarpet/language/SystemFunctions.md
It appears that `replace` and `replace_first` require double backslashes to use some regex operators, probably because it seems that Java also requires this. I've added a note about it to the description of the functions in the docs and also added an example that is similar to the originals. If this requirement is considered a bug and is fixed soon, this pr can be ignored.
> Docs edit, noted double backslash requirement for some regex operators

- .github/workflows/build-on-pr.yml
- .github/workflows/devbuild.yml
- .github/workflows/publish-release.yml
Since a while back, `setup-java` has an option to prepare and restore the cache of gradle packages directly there. It's not only simpler but they also claim for it to be faster given it runs at the same time java is being setup.
In this PR I drop the cache step in favour of adding `setup-java`'s in all three workflows.
> Simplify cache in action workflows

- .gitattributes
Adds a `.gitattributes` file to do that.
Closes #1406.
> Highlight scarpet files with github's highlighter for python

- src/main/java/carpet/script/api/Auxiliary.java
Does that.
There's a very small compatibility risk, where passing empty strings previously would also make it as if `null` was passed, now it only does that for explicit null. I don't think we should consider it, because even if something was using it, the difference in behaviour is minimal, and I don't think it's documented even.
> Add support for formatted names in `create_marker`

- src/main/java/carpet/script/exception/CarpetExpressionException.java
- src/main/java/carpet/script/exception/ExitStatement.java
- src/main/java/carpet/script/exception/ExpressionException.java
- src/main/java/carpet/script/exception/InternalExpressionException.java
- src/main/java/carpet/script/exception/StacklessRuntimeException.java
Resolves #1391.
Does that by introducing an abstract class that doesn't do anything when `fillInStacktrace()` is called, `StacklessRuntimeException`. See the issue for more details.
> Make scarpet internal and control flow exceptions stackless

- src/main/java/carpet/script/CarpetScriptHost.java
Adds the type of the value to the hover over tooltips from the error snooper.
> Show local type in exception hover tooltips

- src/main/java/carpet/CarpetServer.java
- src/main/resources/fabric.mod.json
Does that.
- Since some version fabric loader allows static method references in the json, so let's just use that.
- Adds a warning to extensions that mixin to `CarpetServer#onGameStarted` just to register themselves because it's a very stupid practice when we're maintaining paths to allow them to use a simple `ModInitializer`. It still being allowed only makes more extensions copy the same behaviour ([literally](https://github.com/search?q=CarpetServer+onGameStarted+org.spongepowered.asm.mixin.Mixin&type=code), over 10 extensions are doing this).
- This doesn't try to prevent them from mixing into other places of carpet if they need to (although if they do it's at their own risk)
Also makes the deprecated fallback when extensions register too late throw an exception, given they've been …
> Simplify mod initializers and warn extensions from mixing into Carpet just to register themselves

- build.gradle
- settings.gradle
Also bumps loom QuiltFlower version, given only the latest version is there atm.
Doing this also bumps default QuiltFlower version to [1.8.0](https://github.com/QuiltMC/quiltflower/releases/tag/1.8.0).
> Remove cotton maven given lQF is now on the Gradle plugin portal

- src/main/java/carpet/script/annotation/AnnotationParser.java
- src/main/java/carpet/script/annotation/ScarpetFunction.java
Prevents instantiating classes with all annotated methods static, making it also more flexible in that you can put annotated functions near to other API that may be initialized in special ways.
The docs really need rewriting, but that's for another day, this should be trivial.
This is motivated after discovering that Java doesn't throw binary compatibility errors if an annotation type is missing, just ignores those annotations.
Therefore other mods should be able annotate their already API methods directly without fear of binary issues when carpet isn't present, as long as the call to parseFunctionsClass is wrapped inside a condition. This PR improves this by not adding strange behaviour to parsing a class. Further PRs will try to improve this by adding utils like allowing to change the …
> Ease concrete restrictions on Annotated Scarpet API and make instantiating lazier

- .github/workflows/publish-release.yml
This PR adds a new job to the release action that publishes a proper message to a discord webhook after everything has been built and published (and therefore jars are available at least in github releases). The curseforge URLs aren't added because there's an issue/not implemented feature on github actions where matrix builds only output the results of one branch, and we have up to two.
Image of the result (from the release input from https://github.com/altrisi/fabric-carpet/releases/tag/test3):
Requires the setup of a secret, `DISCORD_BOT_TOKEN`, that I can DM you when you are able to add it to the repo, as I can't manage secrets.
Would also need disabling of releases being posted via github's webhook.
> Publish changelogs to Discord when releasing

- src/main/java/carpet/script/value/EntityValue.java
Fixes #1485 
Basically the `showIcon` variable got set twice, instead of the `ambient` variable being set.
> Set ambient properly in modify(entity, 'effect')

- src/main/resources/assets/carpet/scripts/overlay.sc
Should fix #1447, closes #1283.
Does that by changing the argument type to an identifier, so it allows `:` to be used.
> Allow modded structures in overlay's `structure` renderer

- src/main/java/carpet/helpers/HopperCounter.java
- src/main/java/carpet/mixins/BoundTickingBlockEntity_tickMixin.java
- src/main/java/carpet/mixins/PistonBaseBlock_movableBEMixin.java
- src/main/java/carpet/script/value/NBTSerializableValue.java
- src/main/java/carpet/script/value/ValueConversions.java
- src/main/java/carpet/utils/PerimeterDiagnostics.java
- src/main/java/carpet/utils/SpawnReporter.java
This PR resolves all raw type warnings in the codebase.
It also does a very small optimization to hopper counters and removes some redundant casts in `PerimeterDiagnostics`.
> Resolve raw type warnings

- src/main/java/carpet/utils/SpawnReporter.java
Mostly removes unused code.
With this I think I've understood what most of it is actually doing, so expect a bigger refactor with some optimizations later.
> Minor SpawnReporter cleanup

- .github/workflows/publish-release.yml
Multiple people have reported crashes because this is what CurseForge shows for the latest versions for snapshots:
It was just that they were trying to run it on 1.19 release.
This removes the `Mod` from there so more stuff fits and hopefully helps people not get lost.
> Don't add `Mod` to CF release to prevent cutting game version

- src/main/java/carpet/script/utils/SystemInfo.java
Mods may change their name, but should keep their id. Even carpet changed it once.
There's a small compatibility risk, with apps that use that function, though I haven't been able to find any on github, though maybe it's just it doesn't know how to search scarpet code (or I don't).
> Map from id in `system_info('server_mods')`

- docs/scarpet/resources/editors/npp/scarpet.xml
Basically instead of suggesting `__command` or `__on_player_breaks_block` it will suggest `__command() ->` and `__on_player_breaks_block(player, block) ->`.
Will probs be modified after #1525 is merged (Or I'll modify that, based on which gets merged first)
> Adding arguments to events in Notepad++ docs

- src/main/java/carpet/script/CarpetScriptServer.java
- src/main/java/carpet/script/Module.java
- src/main/java/carpet/script/api/Auxiliary.java
- src/main/java/carpet/script/argument/FileArgument.java
- src/main/java/carpet/script/utils/WorldTools.java
This PR removes all remaining `File` usages (via `Path.toFile()`) barring one, given I've heard that in hot code `Files.exists()` is slower than `toFile().exists()` if in the default `FileSystem`, and that place seemed to be hot given it even used caches. That one is pending investigation to whether it is actually worth, though it'll likely just be kept that way given AFAIK minecraft worlds can only be interacted with in the default filesystem.
It also fixes some resource leaks, given `Stream`s don't `close()` when you call a terminal operation, therefore those created by `Files.list` and `Files.walk` were previously leaking open directories (`DirectoryStream`s are also one of the few resource handlers in Java without a cleanable for closing on gc). Luckily these functions weren't called …
> Remove the last few `File` usages and fix some resource leaks

- src/main/java/carpet/script/argument/FileArgument.java
Should fix #1502.
Windows file system is case-insensitive, so doing a `toLowerCase` on the file names doesn't matter. However, others, such as Linux, do not ignore upper/lower case, so this was preventing scarpet from reading or modifying files that weren't fully lower-case. Luckily I believe files created by scarpet should have gotten lower case given they're handled by this path so they didn't break, but if you put the files by yourself (or through some other code path, if there is) they do.
> Fix handling files with uppercase letters in case-sensitive systems

- src/main/java/carpet/script/CarpetContext.java
- src/main/java/carpet/script/CarpetEventServer.java
- src/main/java/carpet/script/CarpetScriptHost.java
- src/main/java/carpet/script/value/ScreenValue.java
This PR creates an origin-less `CarpetContext` constructor and an origin-less `callUDF` method.
This is done given most callers use `BlockPos.ZERO` anyway, and this argument has led to confusion (and therefore a bug) at least once, plus these may get removed at some point IIRC, so having the definitive ones already is nice.
The PR also migrates usages of the old ones with `BlockPos.ZERO` to these.
The origin is still there so this doesn't break existing behaviour, just in a second place.
> Expose origin-less constructors and methods

- src/main/java/carpet/script/value/ListValue.java
Calling `ArrayList::addAll` after constructing the `ArrayList` will always copy the array returned from `Collection::toArray` (that is always a copy by contract).
However, calling the constructor that takes a `Collection` will just use the array returned by `toArray` if it's trusted that the array is a copy, by checking if the collection was an `ArrayList`, the most likely case.
Therefore, in the common case of an `ArrayList` being passed, there will be a single copy of the array instead of two, and some empty list initialization code will be skipped.
And it also simplifies code a tiny bit.
> Optimize `ListValue::new(Collection)` slightly for best-case scenarios

- src/main/java/carpet/mixins/ClientPacketListener_customPacketsMixin.java
- src/main/java/carpet/mixins/ServerGamePacketListenerImplMixin.java
- src/main/java/carpet/network/CarpetClient.java
- src/main/java/carpet/network/ClientNetworkHandler.java
- src/main/java/carpet/script/utils/ShapesRenderer.java
This PR ensures that Carpet's network handlers are being run on the main thread:
- The client network handler now mixins after the `handleCustomPayload` method has been pushed to the main thread.
- This wasn't direcly causing any concurrency issues but any Carpet Extensions with validators on the client side would be running off-thread and may lead to race conditions, this also would cause any other mods that mixin into Carpet's network handling to have the same issue.
- Since all the shape code is now running on the main thread the maps that store the shapes no longer needed to be synchronized.
- The server network handler now pushes the method to the main thread.
- This could have been the cause for a concurrency issue as `ServerNetworkHandler.remoteCarpetPlayers` gets updated on the …
> Make Carpet's Network Handlers Run On Main Threads

- src/main/java/carpet/script/value/Value.java
Fixes #1542.
From the `Matcher.group(int)` javadoc:
>  If the match was successful but the group specified failed to match any part of the input sequence, then null is returned.
We were taking these nulls to the null-safe `StringValue` constructor, therefore creating broken values. This makes those cases return a scarpet `null`.
I don't know a lot about regex (and its "contracts" in scarpet) so I'm not sure if `null` is the proper return for this kind of cases.
> Fix `in` (`~`) operator producing broken values

- src/main/java/carpet/api/settings/CarpetRule.java
- src/main/java/carpet/api/settings/SettingsManager.java
- src/main/java/carpet/settings/ParsedRule.java
This PR adds the `strict()` method to the `CarpetRule` interface.
If the method returns `true`, that means that the rule won't accept any value other than the ones returned in `CarpetRule#suggestions`. The opposite guarantees nothing.
The interface implements it as a default method (that returns `false`) to allow compatibility with current implementations.
`ParsedRule` implements it by checking that the rule has the `Strict` Validator, given that's how it's implemented now (the `isStrict` boolean just comes from the boolean in the annotation, that doesn't guarantee the rule will actually be strict).
Resolves #1541.
> Allow rules to declare they only accept a set of options

- src/main/java/carpet/script/CarpetEventServer.java
Fixes #1573
This would happen if an event is triggered inside an event (In the case of veinminer, by calling `harvest` inside `__on_player_breaks_block`, which would trigger the event again). This makes `runIfEnabled` return null, which errors when converting `Boolean` to the primitive
> Fixed NPE when events are triggered within events

- src/main/java/carpet/script/Expression.java
Those are relatively expensive to compute, more the bigger apps are.
They're especially expensive in terms of call stack size, given their use of heavily nested `Stream`s (each contributing multiple many to the call stack).
This not only improves compile times, but it also allows for much larger (deep) apps, including the depth that the unoptimized `;` adds.
> Don't compute tree size and depth with debugging disabled

- src/main/java/carpet/CarpetSettings.java
- src/main/java/carpet/mixins/FillBiomeCommandMixin.java
- src/main/resources/carpet.mixins.json
Simply just uses carpet's `fillLimit` as the limit for the `/fillbiome` command.
> Make `/fillbiome` limit customisable with `fillLimit`

- src/main/java/carpet/helpers/OptimizedExplosion.java
Fixed drop decay gamerules work exactly the opposite when using optimized tnt.
> Fixed drop decay gamerules not working properly.

- src/main/java/carpet/script/CarpetScriptHost.java
- src/main/java/carpet/script/CarpetScriptServer.java
Fixes #1634.
Should this make it into a 1.19.3 release? This isn't directly on top of 1.19.3, but it doesn't include any 23w03a commits, so it could be merged into 1.19.3 without many issues by just changing the target branch. Update: Actually it's sitting on top of a commit with an NPE.
The bug is present in all 1.19.3 versions, and on the latest 1.19.2 version. Older versions are unaffected.
> Fix unchecked removal of commands by app name

- src/main/java/carpet/patches/EntityPlayerMPFake.java
Fix fake players not accumulating fallDistance or ever 'hitting the ground'
* Fixes #1586 (Fake player does not take fall damage)
* Should Fix #1478 (fake players cannot use critical hits)
* Should Fix Unreported/Unconfirmed (fake players can not engage Elytras)
Tested in single player and multiplayer (with change applied to 1.19.3 branch), connected to server with a matching modified carpet and 1.19.3 release carpet on client, without any apparent issues.
I do get a crash on the client when I disconnect from a server, but that also happens on a build of 1.19.3 branch with nothing else applied, so I'm claiming it's unrelated ;) Doesn't happen with the current released 1.19.3 version on the client though :shrug:
> Fix fake players not accumulating fallDistance

- src/main/java/carpet/script/annotation/AnnotationParser.java
- src/main/java/carpet/script/annotation/ScarpetFunction.java
Java methods look weird in snake case, this allows annotated methods for the annotation api to have the name of the scarpet function defined in the `@ScarpetFunction` annotation, so their Java name can be different to the one that will be exposed to Scarpet code.
> Allow scarpet function name to be different to annotated method name

- src/main/java/carpet/helpers/EntityPlayerActionPack.java
Fixes #1072
This basically removed two if clauses that made no sense to me. If they were there for a reason, then I'll find another solution, but right now they are the cause of this bug.
Now `/player botname stop` will immediately stop the player's movement.
Todo proper testing.
> Fixing `/player botname stop` with relation to fake player movement

- docs/scarpet/language/Operators.md
- src/main/java/carpet/script/language/Operators.java
Partially resolves #1666.
This PR changes the current `bitwise_shift_right` to do a logic shift instead of arithmetic, and adds `bitwise_arithmetic_shift_right`.
RFC for whether it should be the other way around, logic being the new one added, but I personally think default should be logic.
Pending is either updating the docs to reflect that only the least significant bits of the amount is used (as specified by the JLS and therefore how the operator works), or if we should work around it and allow amounts greater than that by wrapping the operator (passing a number greater than those is useless as it'd just return 0, or 1 if arithmetic and with the MSB being 1).
> Add arithmetic shift, use logic shift in current right shift

- src/main/java/carpet/api/settings/CarpetRule.java
- src/main/java/carpet/api/settings/SettingsManager.java
- src/main/java/carpet/script/CarpetEventServer.java
- src/main/java/carpet/script/external/Carpet.java
Resolves #1671.
Makes the rule change event get triggered from a general rule observer, also moves it into `script.external.Carpet` given it's at least related and to ensure there's no load order issues by loading from SettingsManager, that extensions could access before we are in a late enough state, also removing it from being public.
> Move rule change event into a rule observer and outside the Java api

- src/main/java/carpet/script/annotation/AnnotationParser.java
(This was introduced in cc24f79d47ef260be12a4ca583186ea12907cfdc)
When specifying no function name in the Annotation, the equality check here seems to fail, making the function name actually become `$METHOD_NAME_MARKER$`, breaking extensions that use that Annotation.
https://github.com/gnembon/fabric-carpet/blob/cc24f79d47ef260be12a4ca583186ea12907cfdc/src/main/java/carpet/script/annotation/AnnotationParser.java#L177
I'm not exactly sure why that fails, since it should be the exact same string literal, but i did check with `System.identityHashCode()`, and they returned different numbers.
This simply replaces that with `USE_METHOD_NAME.equals(annotation.functionName())`
> Fixed AnnotationParser not detecting USE_METHOD_NAME

- src/main/java/carpet/helpers/EntityPlayerActionPack.java
As opposed to real player movement.
Closes #1680.
Supersedes and therefore closes #1681.
> Fixing `/player botname stop` with relation to *fake* player movement

- src/main/java/carpet/commands/PlayerCommand.java
- src/main/java/carpet/patches/EntityPlayerMPFake.java
There should be no changes to users.
Changes:
- Use `GameModeArgument` instead of a String with suggestions
- Refactor unnecessary exceptional control flow
- Rename `SupplierWithCommandSyntaxException`
- Rename `tryGetArg` to `getArgOrDefault`
- Don't use supplier for default in `getOrDefault`
- Inline some methods that were the same as a general method just with a specific param
- Use lambda-creating `manipulate` function when possible
- Remove/move some unnecessary checks
- Minor renames to variables to make them clearer
Pending (about argument):
> Cleanup to the `/player` command

- src/main/java/carpet/CarpetSettings.java
- src/main/java/carpet/mixins/MinecraftServer_coreMixin.java
- src/main/java/carpet/mixins/ServerPlayer_scarpetEventMixin.java
- src/main/java/carpet/script/CarpetEventServer.java
- src/main/java/carpet/utils/Messenger.java
- src/main/java/carpet/utils/SpawnChunks.java
- Use `overworld()` instead of `getLevel(Level.OVERWORLD)` when convenient
- Remove now unnecessary `// OW` comments, from when it had no mappings
- Make spawn chunk size and light batches not depend on global server instance
- Merge all spawn chunk size logic into SpawnChunks instead of methods in the validator
- Remove unneeded `withWorld(OVERWORLD)` with just-created server `CommandSource`s
- Use enhanced for in light batch application
> Random cleanups to users of Level.OVERWORLD and reduce `minecraft_server` usage

- src/main/java/carpet/commands/CounterCommand.java
- src/main/java/carpet/helpers/HopperCounter.java
- src/main/java/carpet/utils/WoolTool.java
And some tiny changes to HopperCounter, but a full one of that is pending for some other day.
Changes include:
- Import `Commands.literal`
- Use more readable syntax for Brigadier command
- Use `DyeColor` directly instead of toString -> fromString everywhere
- Also updates WoolTool to use the new `HopperCounter` getter that supports it
- Split `resetCounter` in two, one for single and one for all
As a drive-by change, HopperCounter now uses `overworld()`, and `//OW` comments are removed (from when it was unmapped).
> Cleanup counter command

- src/main/java/carpet/script/language/Sys.java
- src/main/java/carpet/script/value/NumericValue.java
Fixes #1716.
This happens because when doing `NumericValue({thing})`, Java can only choose one constructor to call. Given `double` is "wider" than `long` (it covers both integers and decimals), and it has both of these as possible arguments and can implicitly convert `long`->`double`, Java will consider that a call to `NumericValue(double)` and will cast the `long` to a `double` in the ternary to match the call.
Worth backporting to 1.19.4 imo. Looking for whether there's more stuff we should backport.
Supersedes #1715. Found by @manyrandomthings there from a report on Discord.
> Fix integer operation results being downcasted to floating point

- src/main/java/carpet/patches/EntityPlayerMPFake.java
If a bot is `kill()`ed for a duplicate login, handle the disconnect immediately, Fixes #1468
Fixes player advancements and statistics being unloaded after the player logs back in.
> shadow-player-reconnect-fix

- src/main/resources/assets/carpet/scripts/ai_tracker.sc
As per comments in #1760, box for iron golem spawning range is currently being drawn 1 short in +X and +Z.
Fixes #1760.
> Fix golem spawning range box in ai-tracker

- src/main/java/carpet/script/api/Auxiliary.java
- src/main/java/carpet/script/api/Inventories.java
- src/main/java/carpet/script/api/WorldAccess.java
In 1.18.1 and earlier `item_list()` and `block_list()` would return the list of all items/blocks in registry order, but in 1.18.2 it started to be randomized due to getting the values from the keys of a HashMap. This fix keeps them consistent in the order that they are in the item/block registry.
> Fix registry lists being randomized

- src/main/java/carpet/CarpetSettings.java
- src/main/java/carpet/patches/EntityPlayerMPFake.java
This adds a new Carpet option (`allowListingFakePlayers`) that configures whether fake/bot players are displayed on a player list on the multiplayer screen. When this option is disabled, all fake players will be listed as "Anonymous Player". This fixes #1749.
Previously, this option was always enabled, so fake players were also always displayed on the list. However, recently (I think in `1.20-pre1`), Minecraft changed the internal option to be `false` by default, so fake players are now listed as anonymous. With this PR, the behaviour can now be configured by users.
~~I set `true` as default because this was the old behaviour (until recently). However, I can change it to `false` by default if needed.~~ Now it's `false` by default.
> Add option to configure listing fake players on the multiplayer screen

- src/main/java/carpet/CarpetSettings.java
- src/main/java/carpet/mixins/MinecraftServer_coreMixin.java
- src/main/resources/assets/carpet/lang/fr_fr.json
- src/main/resources/assets/carpet/lang/pt_br.json
- src/main/resources/assets/carpet/lang/zh_tw.json
Resolves #1711.
The rule has been soft-disabled (did nothing) since the new light engine, and the main reason this was added from what I can see is performance, that is better in the new engine.
Not only that, the new default batch size is `1000`, and the main values this rule used to be set were high values, making it seem more pointless.
This PR removes the rule. However, it wouldn't be difficult to make it usable with the new engine if still useful to someone.
> Remove `lightEngineMaxBatchSize` rule

- src/main/java/carpet/patches/FakeClientConnection.java
* override and no-op setListener() in FakeClientConnection
* fixes error spawning bots.
> fix-bots-for-new-networky-bits

- src/main/java/carpet/mixins/LivingEntity_tickSpeedMixin.java
- src/main/resources/carpet.mixins.json
* cancel pushEntities() if game paused
* fixes #1779
Not so targeted an inject as would be nice, but there is far heavier stuff going on here anyway and I think a minor perf hit.
> fix-players-pushing-entities-in-tick-freeze

- src/main/java/carpet/mixins/PistonBaseBlock_movableBEMixin.java
The `PistonBaseBlock#moveBlocks()` method was modified slightly in 1.20.2 causing the mixin target to shift slightly, which causes a crash when a piston moves any block.
> Fix movableBlockEntities crashing in 1.20.2

- docs/scarpet/Full.md
- docs/scarpet/api/Scoreboard.md
- src/main/java/carpet/script/command/CommandArgument.java
The Minecraft Fandom wiki has been forked to a new domain: minecraft.wiki. Learn more here: https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom. This PR updates all URLs accordingly.
> Update Minecraft wiki links to new domain

- src/main/java/carpet/fakes/RecipeManagerInterface.java
- src/main/java/carpet/mixins/RecipeManager_scarpetMixin.java
Fixes #1825 
I'd say warrants a 1.20.2 release.
> Fix hopper counters command error when guessing item color

- src/main/java/carpet/CarpetServer.java
- src/main/java/carpet/CarpetSettings.java
- src/main/java/carpet/script/external/Vanilla.java
Maybe we should add some more generic code for carpet rule -> gamerule migration now that there's so many rules getting going this way.
> Remove `fillLimit` rule and its migration code

- src/main/java/carpet/patches/EntityPlayerMPFake.java
I was getting some off-thread warnings in another mod I'm working on when spawning fake players. 
This lead me to try spamming `/player foobar spawn` in chat, which crashed the game.
I have just changed the `thenAccept` into a `thenAcceptAsync` on the main server thread. This now creates the player and spawns them on the main thread, so there are no more possible race conditions that can happen.
> Fix Race Condition Crash Exploit

- src/main/java/carpet/commands/PlayerCommand.java
- src/main/java/carpet/patches/EntityPlayerMPFake.java
Fixes an issue where repeatedly calling the `createFake` method in quick succession will spawn multiple of the same player which can cause lots of issues. This is because fetching the profile takes some time and the player is not online thus bypasses the logged in check. I've added an extra check for players that are currently being spawned in to prevent further requests to spawn that player in while their profile is being fetched.
> Fixes #1958

- src/main/java/carpet/script/value/EntityValue.java
Setting a player to invulnerable with `modify(player, 'invulnerable', true)` sets the invulnerable ability if the entity value is a player:
https://github.com/gnembon/fabric-carpet/blob/c2f66b12e3e36141d7a6be9ca6de3aa4ea88b8ae/src/main/java/carpet/script/value/EntityValue.java#L1588-L1599
However, querying `player~'invulnerable'` always uses `Entity.isInvulnerable` which won't be true when set via the abilities:
https://github.com/gnembon/fabric-carpet/blob/74e8a8d2eca9e28a67321d6def21cb5a49457471/src/main/java/carpet/script/value/EntityValue.java#L504
That means that this script would return false.
```js
modify(player(), 'invulnerable', true);
query(player(), 'invulnerable'); // => false
```
This PR changes this to return the invulnerable ability for players.
See this thread from the …
> Fixed `e~'invulnerable'` for players

- src/main/java/carpet/mixins/PistonBaseBlock_movableBEMixin.java
The current implementation was breaking polymers block attachments when the blocks were moved by pistons.
This change should fix the issue
> Fix: Compatibility with polymers moving element holders
