gnembon/fabric-carpet

- src/main/java/carpet/mixins/ClientConnectionMixin.java
- src/main/resources/carpet.mixins.json
Added mixins to display the packets sent/received in tab screen.
> Ported /log packets

- src/main/java/carpet/CarpetSettings.java
- src/main/java/carpet/helpers/InventoryHelper.java
- src/main/java/carpet/mixins/ItemEntityMixin.java
- src/main/java/carpet/utils/IItemEntity.java
- src/main/resources/carpet.mixins.json
Ported "stackable empty shulkerboxes on ground" based on @maruohon's tweakeroo code
> Empty stackable shulker boxes

- src/main/java/carpet/CarpetSettings.java
- src/main/java/carpet/fakes/BlockEntityRenderDispatcherInterface.java
- src/main/java/carpet/fakes/PistonBlockEntityInterface.java
- src/main/java/carpet/fakes/WorldChunkInterface.java
- src/main/java/carpet/fakes/WorldInterface.java
- src/main/java/carpet/mixins/BlockEntityRenderDispatcher_movableTEMixin.java
- src/main/java/carpet/mixins/PistonBlockEntityRenderer_movableTEMixin.java
- src/main/java/carpet/mixins/PistonBlockEntity_movableTEMixin.java
- src/main/java/carpet/mixins/PistonBlock_movableTEMixin.java
- src/main/java/carpet/mixins/WorldChunk_movableTEMixin.java
- src/main/java/carpet/mixins/World_movableTEMixin.java
- src/main/resources/carpet.mixins.json
Code by @2No2Name 
Mixins by @DeadlyMC and @2No2Name
> Added movableTE mixins

- src/main/java/carpet/fakes/RedstoneWireBlockInterface.java
- src/main/java/carpet/helpers/RedstoneWireTurbo.java
- src/main/java/carpet/mixins/RedstoneWireBlockMixin.java
- src/main/resources/carpet.mixins.json
Mostly untested, proceed with caution.
> initial pass at rsturbo

- src/main/java/carpet/mixins/PistonHandler_movableTEMixin.java
`direction` was missing `@Final` annotation
> Missing @Final

- src/main/java/carpet/mixins/FlatChunkGeneratorMixin.java
- src/main/java/carpet/settings/CarpetSettings.java
- src/main/resources/carpet.mixins.json
Allows structure mobs to spawn in flat worlds
Potentially closes https://github.com/gnembon/fabric-carpet/issues/84
> Flat worlds structure spawning

- src/main/java/carpet/fakes/TntEntityInterface.java
- src/main/java/carpet/helpers/OptimizedExplosion.java
- src/main/java/carpet/mixins/ExplosionAccessor.java
- src/main/java/carpet/mixins/ExplosionMixin.java
- src/main/java/carpet/mixins/TntEntityMixin.java
- src/main/java/carpet/settings/CarpetSettings.java
- src/main/java/carpet/settings/ParsedRule.java
- src/main/java/carpet/settings/RuleCategory.java
- src/main/resources/carpet.mixins.json
This PR ports the following carpet rules from 1.12:
- optimizeTNT
- tntRandomRange
- hardcodeTNTangle
- mergeTNT
> Ported TNT rules

- src/main/java/carpet/mixins/ContainerMixin.java
Fix by @X-com from carpetmod112
> Fix ctrlQCrafting and autoCrafting duplicating items

- src/main/java/carpet/helpers/TickSpeed.java
- src/main/java/carpet/mixins/MinecraftServer_tickspeedMixin.java
Specifically this is implemented and used in G4mespeed v1.0.4.
> Added a way to ensure tickrate compatibility with other mods. 

- src/main/java/carpet/script/Expression.java
previously used entities_list('all'), changed to entity_list('*')
> Changing filter() function example

- README.md
Should be fairly self-explanatory. I said I'd try writing something in the discord at one point
> Add short explanation & example features to README

- docs/scarpet/Documentation.md
> u forgot to add scoreboard manip to documentation.md

- docs/scarpet/api/Scoreboard.md
> place and objective are the other way around in scarpet as opposed to the documentation

- src/main/java/carpet/logging/logHelpers/TNTLogHelper.java
- src/main/java/carpet/mixins/TntEntityMixin.java
With gametime and order-in-gametick of explosions shown
> More infomation in TNT logging

- src/main/java/carpet/script/value/EntityValue.java
str(entity) returns displayName instead of Name (Fixed)
> Fixed Ticket #225

- src/main/java/carpet/script/value/EntityValue.java
Reverts gnembon/fabric-carpet#226
> Revert "Fixed Ticket #225"

- docs/scarpet/Full.md
- docs/scarpet/api/Entities.md
- src/main/java/carpet/script/value/EntityValue.java
It's like 2 lines, but soo useful
> Allow to query mob category

- src/main/java/carpet/CarpetSettings.java
- src/main/java/carpet/commands/DrawCommand.java
Can you tell me how test to see whether it works?
nvm, i figured out
> Added wacky shapes to draw command

- docs/scarpet/Full.md
- docs/scarpet/api/Entities.md
- src/main/java/carpet/script/value/EntityValue.java
- src/main/java/carpet/utils/MobAI.java
however in sp you cant make yourself jump, but you can spawn a player and make him jump.
Also, you can't read inputted string, so I had to go with gamemode_id
> added gamemode and jumping modifications

- docs/scarpet/Full.md
- docs/scarpet/api/Entities.md
> fixed typo

- src/main/java/carpet/commands/DrawCommand.java
I know, I know, this is not the way to make cuboids, but these are the only two prisms you can make, so I thought, why not.
> Cylinders n cuboids

- src/main/java/carpet/helpers/OptimizedExplosion.java
- src/main/java/carpet/logging/LoggerRegistry.java
- src/main/java/carpet/logging/logHelpers/ExplosionLogHelper.java
- src/main/java/carpet/mixins/ExplosionMixin.java
It will show:
1.gametime of explosion
2.position
3.if any block will be affected
4.pushed entities by explosion
the entities will be showned by its type, position as well as delta speed.
entities with same type, position, and deltaSpeed in a single explosion will be merged into one entry.
> Adding Explosion Logger

- src/main/java/carpet/fakes/HungerManagerInterface.java
- src/main/java/carpet/mixins/HungerManagerMixin_scarpetEventsMixin.java
- src/main/java/carpet/script/value/EntityValue.java
- src/main/resources/carpet.mixins.json
But I can't for the life of me query exhaustion. You're gonna have to do your magic with Interfaces.
Fixes #230
> Added hunger, saturation and exhaustion modification and querying

- docs/scarpet/Full.md
- docs/scarpet/api/BlockIterations.md
- src/main/java/carpet/script/CarpetExpression.java
> Add support for triples of positions in volume

- src/main/resources/assets/carpet/lang/zh_cn.json
Make some translations more accurate and add the translation of `ui.rule_%(rule)s_not_set_restart` in `zh_cn.json`
> zh_cn.json update

- src/main/resources/assets/carpet/lang/zh_cn.json
- src/main/resources/assets/carpet/lang/zh_tw.json
Translated by:Forgot-Dream and X-Green
Time:2020-7-18
> update zh_cn.json and zh_tw.json

- src/main/java/carpet/CarpetSettings.java
- src/main/java/carpet/settings/ParsedRule.java
> added "ops" setting to each rule

- src/main/resources/assets/carpet/lang/zh_cn.json
Just some small fixes & tweaks of punctuation marks/grammar issues/mistranslations.
> Fixes and small tweaks for zh-cn translation

- src/main/java/carpet/mixins/BastionRemnantFeatureMixin.java
idk, it made it not start properly
> Random bug, extra semicolon

- src/main/java/carpet/mixins/BlockStateArgument_fillUpdatesMixin.java
- src/main/resources/carpet.mixins.json
> Fix fillupdates

- src/main/java/carpet/mixins/ServerWorld_tickMixin.java
Tick health shouldn't display blockEvents under the section Village
#401
> Fix #401 (tick health)

- docs/scarpet/api/Entities.md
Moved
<pre>
Run(‘/kill ’ + e~'command_name’);
</pre>
To modify(e, ‘kill’) since that makes more sense than it being at query(e, 'persistence').
> Minor corrections to Entities.md

- docs/scarpet/Full.md
- docs/scarpet/api/Auxiliary.md
- docs/scarpet/api/Entities.md
- src/main/java/carpet/script/CarpetExpression.java
- src/main/java/carpet/script/value/EntityValue.java
Fixes #445 
Im not sure whether it should output error by default, or I should hardcode at 2 by default, or maybe just set it to info by default. I think info makes more sense than warn...
> Updating logger to support different types

- docs/scarpet/resources/editors/idea/4.txt
Update Intellij Custom Language support 4.txt to include arguments and arrow operators for all events.
> Update Intellij Custom Language support

- docs/scarpet/Full.md
- docs/scarpet/api/Scoreboard.md
- docs/scarpet/resources/editors/idea/2.txt
- docs/scarpet/resources/editors/npp/scarpet.xml
- docs/scarpet/resources/editors/npp/scarpet_v1.7_notepad++.xml
- src/main/java/carpet/script/api/Scoreboards.java
- src/main/java/carpet/script/value/EntityValue.java
**Continuation of #559**
*(new branch)*
Added the following functions to deal with teams:
team_list() -> list teams => returns list of teams
team_list(team) -> list players in team => returns list of players, or null if team not found
team_add(team) -> create team => returns team name if sucessfull, otherwise null, if team already exists
team_add(team,player) -> join player to team => returns true if player was added, false if player is already in team
team_remove(team) -> removes team => returns true if team was removed, null if team didnt exist
team_leave(player) -> leaves player out of his team => returns true if player was in a team, false if not
team_empty(team) -> remove all players from team => returns number of players that were in the team, null if team not found …
> Added scarpet team functions

- docs/scarpet/api/Scoreboard.md
- src/main/java/carpet/script/api/Scoreboards.java
Sorry to make a PR for just this ._.
> Fixed small mistakes in team functions

- docs/scarpet/api/Auxiliary.md
- docs/scarpet/resources/editors/idea/2.txt
- docs/scarpet/resources/editors/npp/scarpet.xml
- src/main/java/carpet/script/api/Auxiliary.java
_Title_ says it all.
Works with both `StringValue` and `FormattedTextValue`, and supports custom timings.
See docs for more info.
Should I mention in docs that times are per-player and are (AFAIK) reset when player rejoins?
Also that `subtitle` requires to have a running `title` to be shown?
> [Scarpet] Add display_title function

- src/main/java/carpet/settings/SettingsManager.java
Resolves #211 and resolves #356.
This PR makes Carpet read from a `default_carpet.conf` (or any identifier, for extensions) file if there is no `carpet.conf` in the current's world directory. Since those defaults will also be read when adding new rule defaults (`setDefault` or `removeDefault`), that means that the world's config file, when created, will be a copy of the default plus the new values. The default config files are stored at `[root]/config/carpet/default_carpet.conf` (with root usually being `.minecraft`, but basically install dir).
This functionality is explicitly disabled when Carpet is in a dedicated server, to prevent creating a useless `config/carpet` folder in servers, since those have a single world.
The default `conf` files are explicitly created whenever trying to …
> Add a way to load a default config file

- .gitignore
- docs/scarpet/api/Events.md
- docs/scarpet/api/Overview.md
- src/main/java/carpet/CarpetServer.java
- src/main/java/carpet/commands/ScriptCommand.java
- src/main/java/carpet/script/CarpetEventServer.java
- src/main/java/carpet/script/CarpetScriptHost.java
- src/main/java/carpet/script/CarpetScriptServer.java
- src/main/java/carpet/script/EntityEventsGroup.java
- src/main/java/carpet/script/ScriptHost.java
- src/main/java/carpet/script/api/Auxiliary.java
- src/main/java/carpet/script/value/EntityValue.java
- src/main/resources/assets/carpet/scripts/distance_beta.sc
allowing apps to function more independently and allowing for player scoped apps to handle global events.
> rework of the event system, fixes #596

- docs/scarpet/api/Auxiliary.md
- src/main/java/carpet/script/utils/SystemInfo.java
Its useful in draw app, and may be in other built-ins for debug purposes. Also its cool info to have.
> Adding dev_environment to system_info

- docs/scarpet/api/Auxiliary.md
- src/main/java/carpet/script/utils/SystemInfo.java
It's mostly for WE dev, ngl (see Ghoulboy78/World-edit-scarpet#25, the bit about schematics)
Also, it could be useful elsewhere too.
> Add game_data_version to system_info

- src/main/java/carpet/script/api/Auxiliary.java
This PR adds/changes two things:
- Makes Gson not escape HTML entities, since Scarpet doesn't require HTML safeness and it looks better
- Rethrows JSON parsing/syntax exceptions in a more user-friendly way
Even though it would still be caught higher in the stack, this makes the exception specify what failed and makes it more clear, mostly because _usually_ there are two exceptions there
Converting this (current):
```
Error while evaluating expression: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 11 column 4 path $[9] in system chat at pos 1]
```
to this (PR):
```
Error while evaluating expression:
Failed to read JSON file: Unterminated array at line 11 column 4 path $[9] in system chat at pos 1
```
This misses descriptions …
> JSON support tweaks

- src/main/java/carpet/mixins/VillagerEntity_aiMixin.java
> Modify mixin signature to match 1.16 signature

- docs/scarpet/api/Auxiliary.md
- docs/scarpet/resources/editors/idea/2.txt
- docs/scarpet/resources/editors/npp/scarpet.xml
- src/main/java/carpet/script/api/Auxiliary.java
Allows you to easly manage vanilla data command storage
> Added nbt_storage() scapet function

- docs/scarpet/api/Events.md
I just found an obvious typo. Have a nice day.
> Typo correction

- src/main/java/carpet/CarpetSettings.java
- src/main/java/carpet/mixins/UpdateStructureBlockC2SPacketMixin.java
> Fix for 712

- src/main/java/carpet/CarpetSettings.java
- src/main/java/carpet/mixins/ItemEntityMixin.java
Which fixes [MC-206922](https://bugs.mojang.com/browse/MC-206922)
> Added Rule `lightningKillsDrops`

- docs/scarpet/api/Auxiliary.md
- docs/scarpet/api/BlocksAndWorldAccess.md
- docs/scarpet/api/Inventories.md
- docs/scarpet/api/Scoreboard.md
- docs/scarpet/language/FunctionsAndControlFlow.md
- docs/scarpet/resources/editors/idea/3.txt
- docs/scarpet/resources/editors/npp/scarpet.xml
- src/main/java/carpet/script/Expression.java
- src/main/java/carpet/script/Tokenizer.java
- src/main/java/carpet/script/api/Auxiliary.java
- src/main/java/carpet/script/api/Inventories.java
- src/main/java/carpet/script/api/Scoreboards.java
- src/main/java/carpet/script/api/WorldAccess.java
- src/main/java/carpet/script/exception/ExpressionException.java
- src/main/java/carpet/script/exception/InternalExpressionException.java
- src/main/java/carpet/script/exception/ProcessedThrowStatement.java
- src/main/java/carpet/script/exception/ThrowStatement.java
- src/main/java/carpet/script/exception/Throwables.java
- src/main/java/carpet/script/language/ControlFlow.java
- src/main/java/carpet/script/utils/ShapeDispatcher.java
- src/main/java/carpet/script/value/BlockValue.java
- src/main/java/carpet/script/value/FunctionValue.java
- src/main/java/carpet/script/value/NBTSerializableValue.java
- src/main/java/carpet/script/value/ValueConversions.java
@altrisi your PR is read-only with github, so I needed to make another one. Feel free to compare. Didn't edit the docs yet.
> Exceptions - rework

- src/main/java/carpet/mixins/PlayerEntity_fakePlayersMixin.java
- src/main/resources/carpet.mixins.json
See https://github.com/gnembon/fabric-carpet/issues/745#issuecomment-820600594
> Fixed #745 (Fake Players take no knockback)

- docs/scarpet/api/Entities.md
- src/main/java/carpet/fakes/ClientSettingsC2SPacketInterface.java
- src/main/java/carpet/fakes/ServerPlayerEntityInterface.java
- src/main/java/carpet/mixins/ClientSettingsC2SPacket_scarpetMixin.java
- src/main/java/carpet/mixins/ServerPlayerEntity_scarpetEventMixin.java
- src/main/java/carpet/script/value/EntityValue.java
- src/main/resources/carpet.mixins.json
> Adding query player language

- docs/scarpet/Full.md
- docs/scarpet/api/Entities.md
- src/main/java/carpet/script/value/EntityValue.java
Added ability to modify entity look vector
Resolves #846
> Modify look

- src/main/java/carpet/commands/CounterCommand.java
- src/main/java/carpet/fakes/IngredientInterface.java
- src/main/java/carpet/fakes/RecipeManagerInterface.java
- src/main/java/carpet/helpers/HopperCounter.java
- src/main/java/carpet/mixins/HopperBlockEntityMixin.java
- src/main/java/carpet/utils/WoolTool.java
> Adding Javadocs to CounterCommand.java and relevant files

- docs/scarpet/api/ScriptCommand.md
- src/main/java/carpet/commands/ScriptCommand.java
- src/main/java/carpet/helpers/ScriptDownloader.java
Very much a WIP thing, but a fun project nontheless
Resolves #713 
Tasks:
> Adding /script download

- src/main/java/carpet/CarpetSettings.java
- src/main/java/carpet/mixins/BuddingAmethystBlock_getPistonBehaviorMixin.java
- src/main/resources/carpet.mixins.json
As discussed in Episode 79 of ilmangos peaceful challenge. 
He said he'd do it, I figured I could beat him to the punch. :)
Context: https://youtu.be/0-fAKpr_J8k?t=1180
> Add Movable Amethyst Rule

- src/main/java/carpet/settings/Condition.java
- src/main/java/carpet/settings/Rule.java
- src/main/java/carpet/settings/SettingsManager.java
> Add condition argument to Rule annotation

- src/main/java/carpet/commands/ScriptCommand.java
- src/main/java/carpet/script/utils/AppStoreManager.java
Resolves #985.
Does basically that.
Haven't tested it with a vanilla client, but given it's a brigadier feature I guess it should work?
> Provide script download suggestions async

- src/main/java/carpet/logging/LoggerRegistry.java
> [Useless] Remove Space

- src/main/java/carpet/fakes/WorldInterface.java
- src/main/java/carpet/mixins/LivingEntity_maxCollisionsMixin.java
- src/main/java/carpet/mixins/SpawnHelperMixin.java
- src/main/java/carpet/mixins/World_getOtherEntitiesLimited.java
- src/main/java/carpet/mixins/World_tickMixin.java
- src/main/resources/carpet.mixins.json
> Max collisions optimization

- src/main/java/carpet/script/value/EntityValue.java
> Fix x motion being applied to y

- src/main/java/carpet/commands/PlayerCommand.java
This enables administrators to flexibly spawn players in game modes other than their current modes, and also allows administrators to spawn non-creative players from the console or rcon.
Usage: `/player spawn bot in <gamemode>`
Usage: `/player spawn bot at ~ ~ ~ face 0 0 in minecraft:overworld in <gamemode>`
Permissions required: OP Level 2 and above.
Note on flying: For spectator players, flying is always enabled. For other game modes, whether they are flying depends on the command caller. Therefore, it is possible to spawn a flying survival player when you are currently flying.
> allow specifying game modes when spawning fake players

- README.md
Second iteration of adding badges and icons to the readme (first one was never PRed).
I think it adds interesting information and gives a direct link to the Discord (this made me send the PR), and looks good.
[Quick preview link](https://github.com/altrisi/fabric-carpet/tree/rare-readme-2-electric-boogaloo#readme)
> Add badges and icons to readme

- src/main/java/carpet/script/value/EntityValue.java
Fixed the issue as per the issue description.
> Fix #1161: Typo in extreme velocity log message

- docs/scarpet/api/Entities.md
You can now modify NBT data with `modify nbt_merge` and `modify nbt`
> Outdated comment, unable to modify NBT

- src/main/java/carpet/script/value/EntityValue.java
> Absorption is cast to long, then to float, instead of directly to float

- docs/scarpet/api/Auxiliary.md
- src/main/java/carpet/script/api/Auxiliary.java
- src/main/java/carpet/script/utils/SystemInfo.java
Resolves #1014.
This PR adds properties in `system_info` to get the following parameters associated to the source of the execution:
- Entity
- Position
- Dimension
- Rotation
> Allow apps to retrieve information about the source

- src/main/java/carpet/script/CarpetExpression.java
- src/main/java/carpet/script/CarpetScriptHost.java
Fixes #1198.
Also added some info about how to unpause scarpet to the errors from those cases.
> Improve CarpetExpressionException error messages

- src/main/java/carpet/commands/TickCommand.java
> Give feedback when stepping ticks

- docs/scarpet/api/Auxiliary.md
- src/main/java/carpet/script/utils/SystemInfo.java
> Used wrong method to query world border size

- docs/scarpet/Full.md
- docs/scarpet/api/BlocksAndWorldAccess.md
I encountered some out-of-date documentation while working on https://github.com/gnembon/scarpet/issues/280
> updated documentation for 1.18

- src/main/java/carpet/script/CarpetScriptHost.java
Does that.
Shouldn't conflict with the mojmap refactor.
> Fix `stay_loaded` being `false` in apps with no config

- src/main/java/carpet/CarpetSettings.java
- src/main/resources/assets/carpet/lang/zh_cn.json
Closes #1200
Reopened because #1211 was closed when branch `future` was deleted.
> Feature: simulationDistance rule

- src/main/java/carpet/script/value/ScreenValue.java
Wrong origin in screen callbacks
> Fixed execution offset in screens callback context

- docs/scarpet/api/Events.md
- src/main/java/carpet/mixins/ServerLevel_scarpetMixin.java
- src/main/java/carpet/script/CarpetEventServer.java
Hello it is my first PR on here (hopefully first of many). I just added a `__on_chunk_unloaded` event as requested in #1403
> Added `__on_chunk_unloaded` scarpet event

- src/main/java/carpet/script/language/DataStructures.java
i think it is necessary to make encoding and decoding use the same codec
it is ok that both of them use local encoding.
it is ok that both of them use the same specific encoding.
it is not ok that only one of them use local encoding.
> one-line fix for a minor bug about encoding 

- src/main/java/carpet/script/utils/AppStoreManager.java
The first commit gives up manual locking to just used the built-in `synchronized` lock, that should prevent death locks in case there were any (may fix #1377?).
Second commit makes use of Apache IOUtils in order to download the contents from a URL to a String, instead of using a method that came from external sources (and, tbh, had many things wrong).
> Simplify threading and networking in `download` suggester

- src/main/java/carpet/utils/CarpetProfiler.java
Does that, and to do that also changes a `HashMap<T, Long>` to a `Object2LongOpenHashMap<T>`. Doing that also removes the setting everything to 0 given they default to 0 by themselves.
Similar to in #1519, using `addTo` removes some unnecessary computing, and using a primitive-specific map helps both performance and memory usage.
The PR also changes the way the maps are sorted to use a primitive-specific comparator instead of doing lots of unboxing, two at each comparison.
Ran a few profiles, noticed no issues.
> Merge a few `put(get()+n)` into fastutil's `addTo` to remove hash operations

- src/main/java/carpet/script/api/Auxiliary.java
- src/main/java/carpet/script/api/Entities.java
- src/main/java/carpet/script/api/Inventories.java
- src/main/java/carpet/script/api/Scoreboards.java
- src/main/java/carpet/script/api/WorldAccess.java
- src/main/java/carpet/script/command/CommandArgument.java
- src/main/java/carpet/script/language/ControlFlow.java
- src/main/java/carpet/script/language/DataStructures.java
- src/main/java/carpet/script/language/Functions.java
- src/main/java/carpet/script/utils/BiomeInfo.java
- src/main/java/carpet/script/utils/SystemInfo.java
- src/main/java/carpet/script/value/EntityValue.java
- src/main/java/carpet/script/value/NBTSerializableValue.java
- src/main/java/carpet/script/value/Value.java
- src/main/java/carpet/script/value/ValueConversions.java
Improves readability and unifies Stream to ListValue handling.
> Refactor code to use `ListValue.wrap(Stream)`

- docs/scarpet/api/Auxiliary.md
- src/main/java/carpet/script/utils/SystemInfo.java
Title says it all. Note that it takes into account modifications fro mdatapacks.
> Adding system_info('world_min_spawning_light')

- src/main/java/carpet/script/utils/ShapeDispatcher.java
- src/main/java/carpet/script/utils/ShapesRenderer.java
> Do not load clientside-only classes in serverside ShapeDispatcher code

- src/main/java/carpet/mixins/PlayerList_fakePlayersMixin.java
- src/main/java/carpet/patches/EntityPlayerMPFake.java
* Allow fake players to respawn (to return from the end)
* Fixes #1645 (Fake players get stuck in the end exit portal)
> Fix fake players not being able to respawn for exiting the end

- src/main/java/carpet/commands/PlayerCommand.java
* Disallow shadowing a single player server owner. Fixes #1442
> shadow-single-player-owner-fix:

- src/main/java/carpet/script/utils/PerlinNoiseSampler.java
- src/main/java/carpet/script/utils/SimplexNoiseSampler.java
Does that. Here just to push against master with an older base.
> Reuse the game's `floor` function in noise samplers

- docs/scarpet/api/BlocksAndWorldAccess.md
Continuing to tick the boxes in #837
> Updating Scarpet docs for BlockIterations.md

- jitpack.yml
Updates the Java version in the `jitpack.yml` to `21.0.2-open`
> Update Java in jitpack.yml

- src/main/java/carpet/mixins/ServerGamePacketListenerimpl_connectionMixin.java
- src/main/resources/carpet.mixins.json
Should fix #1903. Kinda hot-fix, would've liked to look more into networking, maybe including the format change issues from around 20.2, but barely got time.
Didn't have time for extensive testing.
> Fix client packets not being received by the server

- README-ES.md
- README.md
- src/main/java/carpet/CarpetSettings.java
- src/main/resources/assets/carpet/lang/es_ar.json
Spanish is one of the most spoken languages in the world, with over 500 million current speakers. I consider it a good idea to implement this language and also add a README to the repository. Love to all the Spanish speakers around the world <3!
> Add 'es_AR' Language and README-ES

- .github/workflows/build-on-pr.yml
- .github/workflows/devbuild.yml
- .github/workflows/publish-release.yml
Workflows containing upload v3 just don't start start now otherwise. Took the opportunity to update the rest. Merging as soon as build passes here.
> Update actions versions

- src/main/java/carpet/mixins/LivingEntity_maxCollisionsMixin.java
> fix crash when using MaxEntityCollisions rule in Singleplayer world
